//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSEDiagnosticFileParser.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[{\"item1\":\".zip\",\"item2\":\"zip\"},{\"item1\":\".tar\",\"item2\":\"tar\"},{\"item1\":\".gz\",\"it" +
            "em2\":\"gz\"}] ")]
        public string ExtractFilesWithExtensions {
            get {
                return ((string)(this["ExtractFilesWithExtensions"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[\r\n{\"Catagory\": \"ZipFile\", \"FilePatterns\": [\".\\\\*.tar\",\".\\\\*.tar.gz\",\".\\\\*.zip\"]," +
            " \"FileParsingClass\": \"DSEDiagnosticFileParser.file_unzip\", \"NodeIdPos\": 0, \"Proc" +
            "essingTaskOption\":\"IgnoreNode\", \"ProcessPriorityLevel\":1000},\r\n{\"Catagory\": \"Com" +
            "mandOutputFile\", \"FilePatterns\": [\".\\\\nodes\\\\*\\\\nodetool\\\\status\"], \"FileParsing" +
            "Class\": \"DSEDiagnosticFileParser.file_nodetool_status\", \"NodeIdPos\": 0, \"Process" +
            "ingTaskOption\":\"IgnoreNode,OnlyOnce\", \"ProcessPriorityLevel\":950},\r\n{\"Catagory\":" +
            " \"CommandOutputFile\", \"FilePatterns\": [\".\\\\nodes\\\\*\\\\dsetool\\\\ring\"], \"FileParsi" +
            "ngClass\": \"DSEDiagnosticFileParser.file_dsetool_ring\", \"NodeIdPos\": 0, \"Processi" +
            "ngTaskOption\":\"IgnoreNode,OnlyOnce\", \"ProcessPriorityLevel\":950},\r\n{\"Catagory\": " +
            "\"CommandOutputFile\", \"FilePatterns\": [\".\\\\nodes\\\\*\\\\nodetool\\\\ring\"], \"FileParsi" +
            "ngClass\": \"DSEDiagnosticFileParser.file_nodetool_ring\", \"NodeIdPos\": 0, \"Process" +
            "ingTaskOption\":\"IgnoreNode,OnlyOnce\", \"ProcessPriorityLevel\":950},\r\n{\"Catagory\":" +
            " \"SystemOutputFile\", \"FilePatterns\": [\".\\\\opscenterd\\\\node_info.json\"], \"FilePar" +
            "singClass\": \"DSEDiagnosticFileParser.json_node_info\", \"NodeIdPos\": -1, \"Processi" +
            "ngTaskOption\":\"AllNodesInDataCenter\",\"ProcessPriorityLevel\":900},\r\n{\"Catagory\": " +
            "\"SystemOutputFile\", \"FilePatterns\": [\".\\\\opscenterd\\\\repair_service.json\"], \"Fil" +
            "eParsingClass\": \"DSEDiagnosticFileParser.json_repair_service\", \"NodeIdPos\": -1, " +
            "\"ProcessingTaskOption\":\"AllNodesInDataCenter\",\"ProcessPriorityLevel\":900},\r\n{\"Ca" +
            "tagory\": \"ConfigurationFile\", \"FilePatterns\": [\".\\\\nodes\\\\*\\\\dse\"], \"FileParsing" +
            "Class\": \"DSEDiagnosticFileParser.file_DSE_env\", \"NodeIdPos\": -1, \"ProcessingTask" +
            "Option\":\"ScanForNode,ParallelProcessingWithinPriorityLevel\",\"ProcessPriorityLeve" +
            "l\":875},\r\n{\"Catagory\": \"ConfigurationFile\", \"FilePatterns\": [\".\\\\nodes\\\\*\\\\*.yam" +
            "l\"], \"FileParsingClass\": \"DSEDiagnosticFileParser.file_yaml\", \"NodeIdPos\": -1, \"" +
            "ProcessingTaskOption\":\"ScanForNode,ParallelProcessingWithinPriorityLevel,Paralle" +
            "lProcessFiles\",\"IgnoreFilesMatchingRegEx\":\"\\\\\\\\cassandra-topology\\\\.yaml\", \"Proc" +
            "essPriorityLevel\":850},\r\n{\"Catagory\": \"ConfigurationFile\", \"FilePatterns\": [\".\\\\" +
            "nodes\\\\*\\\\cassandra-topology.*\"], \"FileParsingClass\": \"DSEDiagnosticFileParser.f" +
            "ile_cassandra_topology\", \"NodeIdPos\": -1, \"ProcessingTaskOption\":\"ScanForNode,Pa" +
            "rallelProcessingWithinPriorityLevel,ParallelProcessFiles\",\"ProcessPriorityLevel\"" +
            ":800},\r\n{\"Catagory\": \"ConfigurationFile\", \"FilePatterns\": [\".\\\\nodes\\\\*\\\\cassand" +
            "ra-rackdc.properties\"], \"FileParsingClass\": \"DSEDiagnosticFileParser.file_cassan" +
            "dra_rackdc_properties\", \"NodeIdPos\": -1, \"ProcessingTaskOption\":\"ScanForNode,Par" +
            "allelProcessingWithinPriorityLevel,ParallelProcessFiles\",\"ProcessPriorityLevel\":" +
            "800},\r\n{\"Catagory\": \"SystemOutputFile\", \"FilePatterns\": [\".\\\\nodes\\\\*\\\\machine-i" +
            "nfo.json\"], \"FileParsingClass\": \"DSEDiagnosticFileParser.json_machine_info\", \"No" +
            "deIdPos\": -1, \"ProcessingTaskOption\":\"ScanForNode,ParallelProcessing,ParallelPro" +
            "cessFiles\", \"ProcessPriorityLevel\":100},\r\n{\"Catagory\": \"SystemOutputFile\", \"File" +
            "Patterns\": [\".\\\\nodes\\\\*\\\\os-info.json\"], \"FileParsingClass\": \"DSEDiagnosticFile" +
            "Parser.json_os_info\", \"NodeIdPos\": -1, \"ProcessingTaskOption\":\"ScanForNode,Paral" +
            "lelProcessing,ParallelProcessFiles\", \"ProcessPriorityLevel\":100},\r\n{\"Catagory\": " +
            "\"SystemOutputFile\", \"FilePatterns\": [\".\\\\nodes\\\\*\\\\os-metrics\\\\cpu.json\"], \"File" +
            "ParsingClass\": \"DSEDiagnosticFileParser.jason_cpu\", \"NodeIdPos\": -1, \"Processing" +
            "TaskOption\":\"ScanForNode,ParallelProcessing,ParallelProcessFiles\", \"ProcessPrior" +
            "ityLevel\":100},\r\n{\"Catagory\": \"SystemOutputFile\", \"FilePatterns\": [\".\\\\nodes\\\\*\\" +
            "\\os-metrics\\\\load_avg.json\"], \"FileParsingClass\": \"DSEDiagnosticFileParser.file_" +
            "load_avg\", \"NodeIdPos\": -1, \"ProcessingTaskOption\":\"ScanForNode,ParallelProcessi" +
            "ng,ParallelProcessFiles\", \"ProcessPriorityLevel\":100},\r\n{\"Catagory\": \"CommandOut" +
            "putFile\", \"FilePatterns\": [\".\\\\nodes\\\\*\\\\agent_version.json\"], \"FileParsingClass" +
            "\": \"DSEDiagnosticFileParser.file_agent_version\", \"NodeIdPos\": -1, \"ProcessingTas" +
            "kOption\":\"ScanForNode,ParallelProcessing,ParallelProcessFiles\", \"ProcessPriority" +
            "Level\":100},\r\n{\"Catagory\": \"SystemOutputFile\", \"FilePatterns\": [\".\\\\nodes\\\\*\\\\ja" +
            "va_system_properties.json\"], \"FileParsingClass\": \"DSEDiagnosticFileParser.json_j" +
            "ava_system_properties\", \"NodeIdPos\": -1, \"ProcessingTaskOption\":\"ScanForNode,Par" +
            "allelProcessing,ParallelProcessFiles\", \"ProcessPriorityLevel\":100},\r\n{\"Catagory\"" +
            ": \"SystemOutputFile\", \"FilePatterns\": [\".\\\\nodes\\\\*\\\\ntp\\\\ntpstat\"], \"FileParsin" +
            "gClass\": \"DSEDiagnosticFileParser.file_ntpstat\", \"NodeIdPos\": -1, \"ProcessingTas" +
            "kOption\":\"ScanForNode,ParallelProcessing,ParallelProcessFiles\", \"ProcessPriority" +
            "Level\":100},\r\n{\"Catagory\": \"SystemOutputFile\", \"FilePatterns\": [\".\\\\nodes\\\\*\\\\nt" +
            "p\\\\ntptime\"], \"FileParsingClass\": \"DSEDiagnosticFileParser.file_ntptime\", \"NodeI" +
            "dPos\": -1, \"ProcessingTaskOption\":\"ScanForNode,ParallelProcessing,ParallelProces" +
            "sFiles\", \"ProcessPriorityLevel\":100},\r\n{\"Catagory\": \"SystemOutputFile\", \"FilePat" +
            "terns\": [\".\\\\nodes\\\\*\\\\java_heap.json\"], \"FileParsingClass\": \"DSEDiagnosticFileP" +
            "arser.json_java_heap\", \"NodeIdPos\": -1, \"ProcessingTaskOption\":\"ScanForNode,Para" +
            "llelProcessing,ParallelProcessFiles\", \"ProcessPriorityLevel\":100},\r\n{\"Catagory\":" +
            " \"SystemOutputFile\", \"FilePatterns\": [\".\\\\nodes\\\\*\\\\os-metrics\\\\memory.json\"], \"" +
            "FileParsingClass\": \"DSEDiagnosticFileParser.json_memory\", \"NodeIdPos\": -1, \"Proc" +
            "essingTaskOption\":\"ScanForNode,ParallelProcessing,ParallelProcessFiles\", \"Proces" +
            "sPriorityLevel\":100},\r\n{\"Catagory\": \"CommandOutputFile\", \"FilePatterns\": [\".\\\\no" +
            "des\\\\*\\\\nodetool\\\\info\"], \"FileParsingClass\": \"DSEDiagnosticFileParser.file_node" +
            "tool_info\", \"NodeIdPos\": -1, \"ProcessingTaskOption\":\"ScanForNode,ParallelProcess" +
            "ing,ParallelProcessFiles\", \"ProcessPriorityLevel\":100},\r\n{\"Catagory\": \"SystemOut" +
            "putFile\", \"FilePatterns\": [\".\\\\nodes\\\\*\\\\conf\\\\location.json\"], \"FileParsingClas" +
            "s\": \"DSEDiagnosticFileParser.json_location\", \"NodeIdPos\": -1, \"ProcessingTaskOpt" +
            "ion\":\"ScanForNode,ParallelProcessing,ParallelProcessFiles\", \"ProcessPriorityLeve" +
            "l\":100},\r\n{\"Catagory\": \"CQLFile\", \"FilePatterns\": [\".\\\\nodes\\\\*\\\\cqlsh\\\\describe" +
            "_schema\"], \"FileParsingClass\": \"DSEDiagnosticFileParser.cql_ddl\", \"NodeIdPos\": -" +
            "1, \"ProcessingTaskOption\":\"ScanForNode,ParallelProcessing\", \"ProcessPriorityLeve" +
            "l\":100},\r\n{\"Catagory\": \"LogFile\", \"FilePatterns\": [\".\\\\nodes\\\\10.1.36.100\\\\logs\\" +
            "\\cassandra\\\\system.log\"], \"FileParsingClass\": \"DSEDiagnosticFileParser.file_cass" +
            "andra_log4net\", \"NodeIdPos\": -1}\r\n]")]
        public string ProcessFileMappings {
            get {
                return ((string)(this["ProcessFileMappings"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{\r\n\"file_nodetool_status\":{\"RegExStrings\":[\"datacenter:\\\\s+([a-z0-9\\\\-_$%+=@!?<>^" +
            "*&]+)\\\\s*\",\r\n\t\t\t\t\t\t\"(un|ul|uj|um|dn|dl|dJ|dm)\\\\s+([a-z0-9.:_\\\\-+%]+)\\\\s+([0-9.]+" +
            ")\\\\s*([0-9a-z]{0,2})\\\\s+(\\\\d+)\\\\s+([0-9?.% ]+)\\\\s+([0-9a-f\\\\-]+)\\\\s+(.+)\"]},\r\n\"f" +
            "ile_ntpstat\":{\"RegExStrings\":[\"synchronised to NTP server\\\\s+\\\\((.+)\\\\).+stratum" +
            "\\\\s+(\\\\d+).+time correct.+within\\\\s+(\\\\d+\\\\s+[a-zA-Z]+).+polling.+every\\\\s+(\\\\d+" +
            "\\\\s+[a-zA-Z]+)\"]},\r\n\"file_ntptime\":{\"RegExStrings\":[\"ntp_adjtime.+frequency\\\\s+(" +
            "[0-9\\\\-.]+\\\\s+[a-zA-Z]+)\\\\,\\\\s+interval\\\\s+([0-9\\\\-.]+\\\\s+[a-zA-Z]+)\\\\,\\\\s+maxim" +
            "um error\\\\s+([0-9\\\\-.]+\\\\s+[a-zA-Z]+)\\\\,\\\\s+estimated error\\\\s+([0-9\\\\-.]+\\\\s+[a" +
            "-zA-Z]+)\\\\,.+time constant\\\\s+([0-9\\\\-.]+)\\\\,\\\\s+precision\\\\s+([0-9\\\\-.]+\\\\s+[a-" +
            "zA-Z]+)\\\\,\\\\s+tolerance\\\\s+([0-9]+\\\\s+[a-zA-Z]+)\",\r\n\t\t\t\t\t\"ntp_gettime.+maximum e" +
            "rror\\\\s+([0-9\\\\-.]+\\\\s+[a-zA-Z]+)\\\\,\\\\s+estimated error\\\\s+([0-9\\\\-.]+\\\\s+[a-zA-" +
            "Z]+)\"]},\r\n\"file_dsetool_ring\":{\"RegExStrings\":[\"([a-z0-9.:_\\\\-+%]+)\\\\s+([a-z0-9\\" +
            "\\-_$%+=@!?<>^*&]+)\\\\s+([a-z0-9\\\\-_$%+=@!?<>^*&]+)\\\\s+([a-z]+)\\\\s+([a-z]+)\\\\s+([a" +
            "-z]+)\\\\s+([a-z]+)\\\\s+([0-9.]+\\\\s*[a-z]{1,2})\\\\s+([0-9.]+\\\\s*\\\\%?|\\\\?)\\\\s+([0-9\\\\" +
            "-]+)\",\r\n\t\t\t\t\t\"([a-z0-9.:_\\\\-+%]+)\\\\s+([a-z0-9\\\\-_$%+=@!?<>^*&]+)\\\\s+([a-z0-9\\\\-_" +
            "$%+=@!?<>^*&]+)\\\\s+([a-z]+)\\\\s+([a-z]+)\\\\s+([a-z]+)\\\\s+([0-9.]+\\\\s*[a-z]{1,2})\\\\" +
            "s+([0-9.]+\\\\s*\\\\%?|\\\\?)\\\\s+([0-9\\\\-]+)\"]},\r\n\"file_nodetool_ring\":{\"RegExStrings\"" +
            ":[\"datacenter:\\\\s+([a-z0-9\\\\-_$%+=@!?<>^*&]+)\\\\s*\",\"\\\\s*([0-9\\\\-]+)\",\r\n\t\t\t\t\t\"([a" +
            "-z0-9.:_\\\\-+%]+)\\\\s+([a-z0-9\\\\-_$%+=@!?<>^*&]+)\\\\s+([a-z]+)\\\\s+([a-z]+)\\\\s+([0-9" +
            ".]+\\\\s*[a-z]{1,2})\\\\s+([0-9.]+\\\\s*\\\\%?|\\\\?)\\\\s+([0-9\\\\-]+)\"]},\r\n\"cql_ddl\":{\"RegE" +
            "xStrings\":[\"^use\\\\s+(?:\\\\\'|\\\\\\\")([a-z0-9\\\\-_$%+=@!?<>^*&]+)(?:\\\\\'|\\\\\\\")\\\\;?$\",\r\n" +
            "\t\t\t\t\"^create\\\\s+(?:keyspace|schema)\\\\s+(?:if\\\\s+not\\\\s+exists\\\\s+)?(?:\\\\\'|\\\\\\\")?" +
            "([a-z0-9\\\\-_$%+=@!?<>^*&]+)(?:\\\\\'|\\\\\\\")?\\\\s+with\\\\s+(replication)\\\\s*\\\\=\\\\s*(\\\\{" +
            ".+\\\\})\\\\s*(?:and\\\\s+(durable_writes)\\\\s*\\\\=\\\\s*(\\\\w+))?\\\\s*\\\\;?$\",\r\n\t\t\t\t\"^create" +
            "\\\\s+(?:table|column\\\\s+family)\\\\s+(?:if\\\\s+not\\\\s+exists\\\\s+)?([a-z0-9\\\\-_$%+=@!" +
            "?<>^*&.\\\\\'\\\\\\\"]+)\\\\s+(?:\\\\(\\\\s*(.+)\\\\s*\\\\)\\\\s+with\\\\s+(.+)|(?:\\\\(\\\\s*(.+)\\\\s*\\\\)" +
            "))\\\\s*\\\\;?$\",\r\n\t\t\t\t\"^create\\\\s+type\\\\s+(?:if\\\\s+not\\\\s+exists\\\\s+)?([a-z0-9\\\\-_$" +
            "%+=@!?<>^*&.\\\\\'\\\\\\\"]+)\\\\s+(?:\\\\(\\\\s*(.+)\\\\s*\\\\))\\\\s*\\\\;?$\",\r\n\t\t\t\t\"^create\\\\s+(cu" +
            "stom\\\\s+)?index\\\\s+(?:if\\\\s+not\\\\s+exists\\\\s+)?([a-z0-9\\\\-_$%+=@!?<>^*&\\\\\'\\\\\\\"]+" +
            ")\\\\s+on\\\\s+([a-z0-9\\\\-_$%+=@!?<>^*&.\\\\\'\\\\\\\"]+)\\\\s+(?:\\\\(\\\\s*(.+)\\\\s*\\\\))(?:\\\\s+u" +
            "sing\\\\s+([a-z0-9\\\\-_$%+=@!?<>^*&.\\\\\'\\\\\\\"]+))?(?:\\\\s+with\\\\s+options\\\\s*\\\\=\\\\s*(." +
            "+))?\\\\s*\\\\;?$\",\r\n\t\t\t\t\"^create\\\\s+materialized\\\\s+view\\\\s+(?:if\\\\s+not\\\\s+exists\\" +
            "\\s+)?([a-z0-9\\\\-_$%+=@!?<>^*&.\\\\\'\\\\\\\"]+)\\\\s+as\\\\s+select\\\\s+(.+)\\\\s+from\\\\s+([a-" +
            "z0-9\\\\-_$%+=@!?<>^*&.\\\\\'\\\\\\\"]+)\\\\s+where\\\\s+(.+)\\\\s+primary\\\\s+key\\\\s*(?:\\\\(\\\\s*" +
            "(.+)\\\\s*\\\\)\\\\s+with\\\\s+(.+)|\\\\(\\\\s*(.+)\\\\s*\\\\))\\\\s*\\\\;?$\",\r\n                    " +
            "                                           \"^create\\\\s+trigger\\\\s+(?:if\\\\s+not\\\\" +
            "s+exists\\\\s+)?([a-z0-9\\\\-_$%+=@!?<>^*&.\\\\\'\\\\\\\"]+)\\\\s+on\\\\s+([a-z0-9\\\\-_$%+=@!?<>" +
            "^*&.\\\\\'\\\\\\\"]+)\\\\s+using\\\\s+(.+)\\\\s*\\\\;?$\"\r\n\t\t\t]}\r\n}")]
        public string DiagnosticFileRegExAssocations {
            get {
                return ((string)(this["DiagnosticFileRegExAssocations"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>password</string>\r\n  <string>monitored_cassandra_pass</string>\r\n</ArrayOfS" +
            "tring>")]
        public global::System.Collections.Specialized.StringCollection ObscureFiledValues {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ObscureFiledValues"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"[
{""Item1"":""_Comments_"",""Item2"":""Item1 is case sensitive. Item2 Canbe a list of file names delimited by comma. Begginning files will be selected only if no later files in the list exist""},
{""Item1"":""SimpleSnitch"",""Item2"":null},
{""Item1"":""RackInferringSnitch"",""Item2"":null},
{""Item1"":""PropertyFileSnitch"",""Item2"":""cassandra-topology.properties""},
{""Item1"":""GossipingPropertyFileSnitch"",""Item2"":""cassandra-topology.properties,cassandra-rackdc.properties""},
{""Item1"":""CloudstackSnitch"",""Item2"":null},
{""Item1"":""GoogleClouldSnitch"",""Item2"":""cassandra-rackdc.properties""},
{""Item1"":""EC2Snitch"",""Item2"":""cassandra-rackdc.properties""},
{""Item1"":""EC2MultiRegionSnitch"",""Item2"":""cassandra-rackdc.properties""},
{""Item1"":""YamlFileNetworkTopologySnitch"",""Item2"":""cassandra-topology.yaml""}
]")]
        public string SnitchFileMappings {
            get {
                return ((string)(this["SnitchFileMappings"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("%-5level [%thread] %date{ISO8601} %F:%L - %msg%n")]
        public string Log4NetConversionPattern {
            get {
                return ((string)(this["Log4NetConversionPattern"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>mscorlib.dll</string>
  <string>System.dll</string>
  <string>System.Core.dll</string>
  <string>--[Search([AssemblyDir];[WorkingDir];[AppRunTimeDir],DSEDiagnosticLibrary.dll)]</string>
  <string>--[Search([AssemblyDir];[WorkingDir];[AppRunTimeDir],DSEDiagnosticLog4NetParser.dll)]</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection CodeDomAssemblies {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["CodeDomAssemblies"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using DSEDiagnosticFileParser;
using DSEDiagnosticLibrary;
using DSEDiagnosticLog4NetParser;

public static class {0}
{{
    public static {1} {2} ( {3} )
    {{
        {4}
    }}
}}")]
        public string CodeDomClassTemplate {
            get {
                return ((string)(this["CodeDomClassTemplate"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{\"LogClass\":\"file_cassandra_log4net\",\"Parsers\":\r\n\t[ {\"MatchVersion\":null,\r\n\t\t\"Lev" +
            "elMatch\":{\"RegExStrings\":[\"INFO\"]},\r\n\t\t\"ThreadIdMatch\":null,\r\n\t\t\"FileNameMatch\":" +
            "{\"RegExStrings\":[\"^CompactionTask.java$\"]},\r\n\t\t\"FileLineMatch\":null,\r\n\t\t\"Message" +
            "Match\":{\"RegExStrings\":[\"^Compacted\\\\s\\\\d+\\\\ssstables.+$\"]},\r\n\t\t\"ParseMessage\":{" +
            "\"RegExStrings\":[\"^Compacted\\\\s(?<sstables>\\\\d+)\\\\ssstables\\\\sto\\\\s\\\\[(?<SSTABLEP" +
            "ATHS>[a-z0-9\\\\-_@#/.,\\\\ +%]+)\\\\]\\\\.\\\\s+(?<size>\\\\d+\\\\s+[a-z]+)\\\\s+to\\\\s+(?<newsi" +
            "ze>\\\\d+)\\\\s\\\\([0-9a-z\\\\ %~,.]+\\\\)+\\\\sin\\\\s+(?<DURATION>\\\\d+ms)\\\\s*\\\\=\\\\s*(?<iora" +
            "te>[0-9.,]+\\\\s*[a-z/]+)\\\\.\\\\s+(?<totalpartions>\\\\d+)\\\\s+total\\\\s+partitions\\\\s+m" +
            "erged\\\\s+to\\\\s+(?<mergedpartitions>\\\\d+)\\\\.\\\\s+Partition\\\\s+merge\\\\s+counts\\\\s+w" +
            "ere\\\\s+\\\\{(?<mergecounts>[0-9:\\\\ ,]+)\\\\s*\\\\}$\"]},\r\n\t\t\"ParseThreadId\":null,\r\n\t\t\"E" +
            "ventType\":\"SessionEnd\",\r\n\t\t\"EventClass\":\"Compaction\",\r\n\t\t\"SubClass\":null,\r\n\t\t\"Pr" +
            "oduct\":\"Cassandra\",\r\n\t\t\"SessionKey\":\"ThreadId\",\r\n\t\t\"Examples\":[\"INFO  [Compactio" +
            "nExecutor:3211] 2017-01-16 13:33:04,872  CompactionTask.java:141 - Compacting [S" +
            "STableReader(path=\'/var/lib/cassandra/data/system/compactions_in_progress-55080a" +
            "b05d9c388690a4acb25fe1f77b/system-compactions_in_progress-ka-90586-Data.db\'), SS" +
            "TableReader(path=\'/var/lib/cassandra/data/system/compactions_in_progress-55080ab" +
            "05d9c388690a4acb25fe1f77b/system-compactions_in_progress-ka-90588-Data.db\'), SST" +
            "ableReader(path=\'/var/lib/cassandra/data/system/compactions_in_progress-55080ab0" +
            "5d9c388690a4acb25fe1f77b/system-compactions_in_progress-ka-90587-Data.db\'), SSTa" +
            "bleReader(path=\'/var/lib/cassandra/data/system/compactions_in_progress-55080ab05" +
            "d9c388690a4acb25fe1f77b/system-compactions_in_progress-ka-90589-Data.db\')]\",\r\n\t\t" +
            "\t    \"INFO  [CompactionExecutor:3211] 2017-01-16 13:33:06,380  CompactionTask.ja" +
            "va:274 - Compacted 4 sstables to [/var/lib/cassandra/data/system/compactions_in_" +
            "progress-55080ab05d9c388690a4acb25fe1f77b/system-compactions_in_progress-ka-9059" +
            "0,].  590 bytes to 196 (~33% of original) in 15ms = 0.012461MB/s.  3 total parti" +
            "tions merged to 2.  Partition merge counts were {1:1, 2:1, }\",\r\n\t\t\t    \r\n\t\t\t    " +
            "\"INFO  [CompactionExecutor:734] 2017-02-11 23:58:47,586  CompactionTask.java:141" +
            " - Compacting [SSTableReader(path=\'/data/cassandra/data/usprodsec/session_3-ca53" +
            "1e218ed211e6ab872748a53d9d02/usprodsec-session_3-ka-78735-Data.db\'), SSTableRead" +
            "er(path=\'/data/cassandra/data/usprodsec/session_3-ca531e218ed211e6ab872748a53d9d" +
            "02/usprodsec-session_3-ka-78732-Data.db\'), SSTableReader(path=\'/data/cassandra/d" +
            "ata/usprodsec/session_3-ca531e218ed211e6ab872748a53d9d02/usprodsec-session_3-ka-" +
            "78734-Data.db\'), SSTableReader(path=\'/data/cassandra/data/usprodsec/session_3-ca" +
            "531e218ed211e6ab872748a53d9d02/usprodsec-session_3-ka-78733-Data.db\')]\",\r\n\t\t\t   " +
            " \"INFO  [CompactionExecutor:734] 2017-02-11 23:58:47,668  ColumnFamilyStore.java" +
            ":905 - Enqueuing flush of compactions_in_progress: 164 (0%) on-heap, 0 (0%) off-" +
            "heap\",\r\n\t\t\t    \"INFO  [CompactionExecutor:734] 2017-02-11 23:58:47,715  Compacti" +
            "onTask.java:274 - Compacted 4 sstables to[/ data / cassandra / data / usprodsec " +
            "/ session_3 - ca531e218ed211e6ab872748a53d9d02 / usprodsec - session_3 - ka - 78" +
            "741,].  3,541 bytes to 1,079 (~30% of original) in 128ms = 0.008039MB/s.  35 tot" +
            "al partitions merged to 12.  Partition merge counts were {1:1, 3:10, 4:1, }\"    " +
            "    \r\n\t\t\t    ]\r\n\t\t},\r\n\t   {\"MatchVersion\":null,\r\n\t\t\"LevelMatch\":{\"RegExStrings\":" +
            "[\"INFO\"]},\r\n\t\t\"ThreadIdMatch\":null,\r\n\t\t\"FileNameMatch\":{\"RegExStrings\":[\"^Compac" +
            "tionTask.java$\"]},\r\n\t\t\"FileLineMatch\":null,\r\n\t\t\"MessageMatch\":{\"RegExStrings\":[\"" +
            "^Compacting\\\\s+\\\\[$\"]},\r\n\t\t\"ParseMessage\":{\"RegExStrings\":[\"^Compacting\\\\s+\\\\[(?" +
            ":SSTableReader\\\\s*\\\\(\\\\s*path\\\\s*=\\\\s*\'\\\\s*(?<SSTABLEPATH>[a-z0-9\\\\-_@#/.,\\\\ +%]" +
            "+)\\\\s*\'\\\\s*\\\\),?\\\\s*)+\\\\s*\\\\]$\"]},\r\n\t\t\"ParseThreadId\":null,\r\n\t\t\"EventType\":\"Sess" +
            "ionBegin\",\r\n\t\t\"EventClass\":\"Compaction\",\r\n\t\t\"SubClass\":null,\r\n\t\t\"Product\":\"Cassa" +
            "ndra\",\r\n\t\t\"SessionKey\":\"ThreadId\",\r\n\t\t\"Examples\":[\"INFO  [CompactionExecutor:321" +
            "1] 2017-01-16 13:33:04,872  CompactionTask.java:141 - Compacting [SSTableReader(" +
            "path=\'/var/lib/cassandra/data/system/compactions_in_progress-55080ab05d9c388690a" +
            "4acb25fe1f77b/system-compactions_in_progress-ka-90586-Data.db\'), SSTableReader(p" +
            "ath=\'/var/lib/cassandra/data/system/compactions_in_progress-55080ab05d9c388690a4" +
            "acb25fe1f77b/system-compactions_in_progress-ka-90588-Data.db\'), SSTableReader(pa" +
            "th=\'/var/lib/cassandra/data/system/compactions_in_progress-55080ab05d9c388690a4a" +
            "cb25fe1f77b/system-compactions_in_progress-ka-90587-Data.db\'), SSTableReader(pat" +
            "h=\'/var/lib/cassandra/data/system/compactions_in_progress-55080ab05d9c388690a4ac" +
            "b25fe1f77b/system-compactions_in_progress-ka-90589-Data.db\')]\",\r\n\t\t\t    \"INFO  [" +
            "CompactionExecutor:3211] 2017-01-16 13:33:06,380  CompactionTask.java:274 - Comp" +
            "acted 4 sstables to [/var/lib/cassandra/data/system/compactions_in_progress-5508" +
            "0ab05d9c388690a4acb25fe1f77b/system-compactions_in_progress-ka-90590,].  590 byt" +
            "es to 196 (~33% of original) in 15ms = 0.012461MB/s.  3 total partitions merged " +
            "to 2.  Partition merge counts were {1:1, 2:1, }\"\r\n\t\t\t    \r\n\t\t\t    \"INFO  [Compac" +
            "tionExecutor:734] 2017-02-11 23:58:47,586  CompactionTask.java:141 - Compacting " +
            "[SSTableReader(path=\'/data/cassandra/data/usprodsec/session_3-ca531e218ed211e6ab" +
            "872748a53d9d02/usprodsec-session_3-ka-78735-Data.db\'), SSTableReader(path=\'/data" +
            "/cassandra/data/usprodsec/session_3-ca531e218ed211e6ab872748a53d9d02/usprodsec-s" +
            "ession_3-ka-78732-Data.db\'), SSTableReader(path=\'/data/cassandra/data/usprodsec/" +
            "session_3-ca531e218ed211e6ab872748a53d9d02/usprodsec-session_3-ka-78734-Data.db\'" +
            "), SSTableReader(path=\'/data/cassandra/data/usprodsec/session_3-ca531e218ed211e6" +
            "ab872748a53d9d02/usprodsec-session_3-ka-78733-Data.db\')]\",\r\n\t\t\t    \"INFO  [Compa" +
            "ctionExecutor:734] 2017-02-11 23:58:47,668  ColumnFamilyStore.java:905 - Enqueui" +
            "ng flush of compactions_in_progress: 164 (0%) on-heap, 0 (0%) off-heap\",\r\n\t\t\t   " +
            " \"INFO  [CompactionExecutor:734] 2017-02-11 23:58:47,715  CompactionTask.java:27" +
            "4 - Compacted 4 sstables to[/ data / cassandra / data / usprodsec / session_3 - " +
            "ca531e218ed211e6ab872748a53d9d02 / usprodsec - session_3 - ka - 78741,].  3,541 " +
            "bytes to 1,079 (~30% of original) in 128ms = 0.008039MB/s.  35 total partitions " +
            "merged to 12.  Partition merge counts were {1:1, 3:10, 4:1, }\"        \r\n\t\t\t    ]" +
            "\r\n\t\t},\r\n\t\t{\"MatchVersion\":null,\r\n\t\t\t\t\"LevelMatch\":{\"RegExStrings\":[\"INFO\"]},\r\n\t\t" +
            "\t\t\"ThreadIdMatch\":null,\r\n\t\t\t\t\"FileNameMatch\":{\"RegExStrings\":[\"^ColumnFamilyStor" +
            "e.java$\"]},\r\n\t\t\t\t\"FileLineMatch\":{\"RegExStrings\":[\"^905$\"]},\r\n\t\t\t\t\"MessageMatch\"" +
            ":{\"RegExStrings\":[\"^Enqueuing\\\\s+flush\\\\s+of\\\\s+compactions_in_progress\\\\:.+$\"]}" +
            ",\r\n\t\t\t\t\"ParseMessage\":{\"RegExStrings\":[\"^Enqueuing\\\\s+flush\\\\s+of\\\\s+compactions" +
            "_in_progress\\\\s*\\\\:\\\\s+(?<onheap_bytes>[0-9]+)\\\\s+\\\\((?<onheappercent>[0-9]+\\\\%)" +
            "\\\\)\\\\s+on-heap,\\\\s+(?<offheap_bytes>[0-9]+)\\\\s+\\\\((?<offheappercent>[0-9]+\\\\%)\\\\" +
            ")\\\\s\"]},\r\n\t\t\t\t\"ParseThreadId\":null,\r\n\t\t\t\t\"EventType\":\"SessionItem\",\r\n\t\t\t\t\"EventC" +
            "lass\":\"Compaction\",\r\n\t\t\t\t\"SubClass\":null,\r\n\t\t\t\t\"Product\":\"Cassandra\",\r\n\t\t\t\t\"Sess" +
            "ionKey\":\"ThreadId\",\r\n\t\t\t\t\"Examples\":[\"INFO  [CompactionExecutor:3211] 2017-01-16" +
            " 13:33:04,872  CompactionTask.java:141 - Compacting [SSTableReader(path=\'/var/li" +
            "b/cassandra/data/system/compactions_in_progress-55080ab05d9c388690a4acb25fe1f77b" +
            "/system-compactions_in_progress-ka-90586-Data.db\'), SSTableReader(path=\'/var/lib" +
            "/cassandra/data/system/compactions_in_progress-55080ab05d9c388690a4acb25fe1f77b/" +
            "system-compactions_in_progress-ka-90588-Data.db\'), SSTableReader(path=\'/var/lib/" +
            "cassandra/data/system/compactions_in_progress-55080ab05d9c388690a4acb25fe1f77b/s" +
            "ystem-compactions_in_progress-ka-90587-Data.db\'), SSTableReader(path=\'/var/lib/c" +
            "assandra/data/system/compactions_in_progress-55080ab05d9c388690a4acb25fe1f77b/sy" +
            "stem-compactions_in_progress-ka-90589-Data.db\')]\",\r\n\t\t\t\t\t    \"INFO  [CompactionE" +
            "xecutor:3211] 2017-01-16 13:33:06,380  CompactionTask.java:274 - Compacted 4 sst" +
            "ables to [/var/lib/cassandra/data/system/compactions_in_progress-55080ab05d9c388" +
            "690a4acb25fe1f77b/system-compactions_in_progress-ka-90590,].  590 bytes to 196 (" +
            "~33% of original) in 15ms = 0.012461MB/s.  3 total partitions merged to 2.  Part" +
            "ition merge counts were {1:1, 2:1, }\"\r\n\t\t\t\t\t    \r\n\t\t\t\t\t    \"INFO  [CompactionExe" +
            "cutor:734] 2017-02-11 23:58:47,586  CompactionTask.java:141 - Compacting [SSTabl" +
            "eReader(path=\'/data/cassandra/data/usprodsec/session_3-ca531e218ed211e6ab872748a" +
            "53d9d02/usprodsec-session_3-ka-78735-Data.db\'), SSTableReader(path=\'/data/cassan" +
            "dra/data/usprodsec/session_3-ca531e218ed211e6ab872748a53d9d02/usprodsec-session_" +
            "3-ka-78732-Data.db\'), SSTableReader(path=\'/data/cassandra/data/usprodsec/session" +
            "_3-ca531e218ed211e6ab872748a53d9d02/usprodsec-session_3-ka-78734-Data.db\'), SSTa" +
            "bleReader(path=\'/data/cassandra/data/usprodsec/session_3-ca531e218ed211e6ab87274" +
            "8a53d9d02/usprodsec-session_3-ka-78733-Data.db\')]\",\r\n\t\t\t\t\t    \"INFO  [Compaction" +
            "Executor:734] 2017-02-11 23:58:47,668  ColumnFamilyStore.java:905 - Enqueuing fl" +
            "ush of compactions_in_progress: 164 (0%) on-heap, 0 (0%) off-heap\",\r\n\t\t\t\t\t    \"I" +
            "NFO  [CompactionExecutor:734] 2017-02-11 23:58:47,715  CompactionTask.java:274 -" +
            " Compacted 4 sstables to[/ data / cassandra / data / usprodsec / session_3 - ca5" +
            "31e218ed211e6ab872748a53d9d02 / usprodsec - session_3 - ka - 78741,].  3,541 byt" +
            "es to 1,079 (~30% of original) in 128ms = 0.008039MB/s.  35 total partitions mer" +
            "ged to 12.  Partition merge counts were {1:1, 3:10, 4:1, }\"        \r\n\t\t\t\t\t    ]\r" +
            "\n\t\t},\r\n\t{\"MatchVersion\":null,\r\n\t\t\t\"LevelMatch\":{\"RegExStrings\":[\"INFO\"]},\r\n\t\t\t\"T" +
            "hreadIdMatch\":null,\r\n\t\t\t\"FileNameMatch\":{\"RegExStrings\":[\"^ColumnFamilyStore.jav" +
            "a$\"]},\r\n\t\t\t\"FileLineMatch\":{\"RegExStrings\":[\"^1211$\"]},,\r\n\t\t\t\"MessageMatch\":{\"Re" +
            "gExStrings\":[\"^Flushing\\\\s+largest\\\\s+\\\\w+\\\\s*\\\\(\"]},\r\n\t\t\t\"ParseMessage\":{\"RegEx" +
            "Strings\":[\"^Flushing\\\\s+largest\\\\s+\\\\w+\\\\s*\\\\(\\\\s*Keyspace\\\\s*=\\\\s*\'?(?<KEYSPACE" +
            ">[a-z0-9\\\\\\\\-_$%+=!?<>^*&@]+)\'?,\\\\s+\\\\w+\\\\s*=\\\\s*\'?(?<DDLITEMNAME>[a-z0-9\\\\\\\\-_$" +
            "%+=!?<>^*&@]+)\'?\\\\)\\\\s+to\\\\s+(?<reason>[^.]+)\\\\.\\\\s+Used\\\\s+total:\\\\s+(?<totalth" +
            "resholdonheap>[0-9.]+)\\\\s*/\\\\s*(?<totalthresholdoffheap>[0-9.]+)\\\\s*,\\\\s*live:\\\\" +
            "s+(?<livethresholdonheap>[0-9.]+)\\\\s*/\\\\s*(?<livethresholdoffheap>[0-9.]+)\\\\s*,\\" +
            "\\s+flushing:\\\\s+(?<flushthresholdonheap>[0-9.]+)\\\\s*/\\\\s*(?<flushthresholdoffhea" +
            "p>[0-9.]+)\\\\s*,\\\\s+this:\\\\s+(?<thisthresholdonheap>[0-9.]+)\\\\s*/\\\\s*(?<thisthres" +
            "holdoffheap>[0-9.]+)$\"]},\r\n\t\t\t\"ParseThreadId\":null,\r\n\t\t\t\"EventType\":\"SessionBegi" +
            "n\",\r\n\t\t\t\"EventClass\":\"MemtableFlush\",\r\n\t\t\t\"SubClass\":null,\r\n\t\t\t\"Product\":\"Cassan" +
            "dra\",\r\n\t\t\t\"SessionKey\":\"DDLITEMNAME\",\r\n\t\t\t\"Examples\":[\"=> INFO  [SlabPoolCleaner" +
            "] 2017-01-16 13:51:50,636  ColumnFamilyStore.java:1211 - Flushing largest CFS(Ke" +
            "yspace=\'OpsCenter\', ColumnFamily=\'rollup_state\') to free up room. Used total: 0." +
            "33/0.00, live: 0.33/0.00, flushing: 0.00/0.00, this: 0.14/0.14\",\r\n\t\t\t\t    \"INFO " +
            " [SlabPoolCleaner] 2017-01-16 13:51:50,636  ColumnFamilyStore.java:905 - Enqueui" +
            "ng flush of rollup_state: 221288084 (14%) on-heap, 0 (0%) off-heap\",\r\n\t\t\t\t    \"I" +
            "NFO  [MemtableFlushWriter:8021] 2017-01-16 13:51:50,637  Memtable.java:347 - Wri" +
            "ting Memtable-rollup_state@1750499154(8.948MiB serialized bytes, 3237264 ops, 14" +
            "%/0% of on/off-heap limit)\",\r\n\t\t\t\t    \"INFO  [MemtableFlushWriter:8021] 2017-01-" +
            "16 13:51:51,353  Memtable.java:382 - Completed flushing /var/lib/cassandra/data/" +
            "OpsCenter/rollup_state-9b934af0746111e68dd04f228b4be406/OpsCenter-rollup_state-t" +
            "mp-ka-7811-Data.db (1.797MiB) for commitlog position ReplayPosition(segmentId=14" +
            "83996065725, position=29889014)\",\t\t\t\t    \r\n\t\t\t\t  ]\r\n\t\t}.\r\n\t{\"MatchVersion\":null," +
            "\r\n\t\t\"LevelMatch\":{\"RegExStrings\":[\"INFO\"]},\r\n\t\t\"ThreadIdMatch\":null,\r\n\t\t\"FileNam" +
            "eMatch\":{\"RegExStrings\":[\"^ColumnFamilyStore.java$\"]},\r\n\t\t\"FileLineMatch\":{\"RegE" +
            "xStrings\":[\"^905$\"]},,\r\n\t\t\"MessageMatch\":{\"RegExStrings\":[\"^Enqueuing\\\\s+flush\\\\" +
            "s+\"]},\r\n\t\t\"ParseMessage\":{\"RegExStrings\":[\"^Enqueuing\\\\s+flush\\\\s+of\\\\s+Memtable" +
            "\\\\-(?<KEYSPACE>[a-z0-9\'\\\\-_$%+=!?<>^*&@]+)\\\\.(?<DDLITEMNAME>[a-z0-9\'\\\\-_$%+=!?<>" +
            "^*&@]+)\\\\@\\\\d+\\\\((?<onheapserialized_bytes>\\\\d+)\\\\/(?<onheap_bytes>\\\\d+)\\\\s+\\\\w+" +
            "\\\\/\\\\w+\\\\s+\\\\w+,\\\\s+(?<operationspersec>\\\\d+\\\\s+[a-z]+)\\\\s*\\\\)\",\r\n\t\t\t\t\t\t\"^Enqueu" +
            "ing\\\\s+flush\\\\s+of\\\\s+(?<DDLITEMNAME>[a-z0-9\'\\\\-_$%+=@!?<>^*&]+)\\\\s*\\\\:\\\\s+(?<on" +
            "heap_bytes>[0-9]+)\\\\s+\\\\((?<onheappercent>[0-9]+\\\\%)\\\\)\\\\s+on-heap,\\\\s+(?<offhea" +
            "p_bytes>[0-9]+)\\\\s+\\\\((?<offheappercent>[0-9]+\\\\%)\\\\)\\\\s\"]},\r\n\t\t\"ParseThreadId\":" +
            "null,\r\n\t\t\"EventType\":\"SessionBeginOrItem\",\r\n\t\t\"EventClass\":\"MemtableFlush\",\r\n\t\t\"" +
            "SubClass\":null,\r\n\t\t\"Product\":\"Cassandra\",\r\n\t\t\"SessionKey\":\"DDLITEMNAME\",\r\n\t\t\"Exa" +
            "mples\":[\"=> INFO  [ValidationExecutor:800] 2017-01-16 13:34:06,722  ColumnFamily" +
            "Store.java:905 - Enqueuing flush of push_device: 2202847 (0%) on-heap, 0 (0%) of" +
            "f-heap\",\r\n\t\t\t    \"INFO  [MemtableFlushWriter:8011] 2017-01-16 13:34:06,722  Memt" +
            "able.java:347 - Writing Memtable-push_device@1288484782(622.872KiB serialized by" +
            "tes, 10486 ops, 0%/0% of on/off-heap limit)\",\r\n\t\t\t    \"INFO  [MemtableFlushWrite" +
            "r:8011] 2017-01-16 13:34:06,762  Memtable.java:382 - Completed flushing /var/lib" +
            "/cassandra/data/push/push_device-109860416f0511e6aeacd54e2d191f81/push-push_devi" +
            "ce-tmp-ka-278155-Data.db (147.118KiB) for commitlog position ReplayPosition(segm" +
            "entId=1483996065722, position=19434795)\",\r\n\t\t\t    \r\n\t\t\t    \"INFO  [AntiEntropySt" +
            "age:1] 2017-01-16 13:34:17,620  ColumnFamilyStore.java:905 - Enqueuing flush of " +
            "push_device: 264396 (0%) on-heap, 0 (0%) off-heap\",\r\n\t\t\t    \"INFO  [MemtableFlus" +
            "hWriter:8011] 2017-01-16 13:34:17,621  Memtable.java:347 - Writing Memtable-push" +
            "_device@1330163944(63.895KiB serialized bytes, 1327 ops, 0%/0% of on/off-heap li" +
            "mit)\",\r\n\t\t\t    \"INFO  [MemtableFlushWriter:8011] 2017-01-16 13:34:17,628  Memtab" +
            "le.java:382 - Completed flushing /var/lib/cassandra/data/push/push_device-109860" +
            "416f0511e6aeacd54e2d191f81/push-push_device-tmp-ka-278156-Data.db (16.152KiB) fo" +
            "r commitlog position ReplayPosition(segmentId=1483996065722, position=19845421)\"" +
            ",\r\n\t\t\t    \r\n\t\t\t    \"INFO  [STREAM-IN-/10.198.59.26] 2017-01-16 13:34:17,795  Col" +
            "umnFamilyStore.java:905 - Enqueuing flush of push_device: 7762 (0%) on-heap, 0 (" +
            "0%) off-heap\",\r\n\t\t\t    \"INFO  [MemtableFlushWriter:8012] 2017-01-16 13:34:17,796" +
            "  Memtable.java:347 - Writing Memtable-push_device@1956470048(2.617KiB serialize" +
            "d bytes, 22 ops, 0%/0% of on/off-heap limit)\",\r\n\t\t\t    \"INFO  [MemtableFlushWrit" +
            "er:8012] 2017-01-16 13:34:17,797  Memtable.java:382 - Completed flushing /var/li" +
            "b/cassandra/data/push/push_device-109860416f0511e6aeacd54e2d191f81/push-push_dev" +
            "ice-tmp-ka-278157-Data.db (0.000KiB) for commitlog position ReplayPosition(segme" +
            "ntId=1483996065722, position=19852124)\",\r\n\t\t\t    \r\n\t\t\t    \"INFO  [CompactionExec" +
            "utor:3211] 2017-01-16 13:34:17,817  ColumnFamilyStore.java:905 - Enqueuing flush" +
            " of compactions_in_progress: 1315 (0%) on-heap, 0 (0%) off-heap\",\r\n\t\t\t    \"INFO " +
            " [MemtableFlushWriter:8011] 2017-01-16 13:34:17,849  Memtable.java:347 - Writing" +
            " Memtable-compactions_in_progress@1461142581(0.146KiB serialized bytes, 9 ops, 0" +
            "%/0% of on/off-heap limit)\",\r\n\t\t\t    \"INFO  [MemtableFlushWriter:8011] 2017-01-1" +
            "6 13:34:17,850  Memtable.java:382 - Completed flushing /var/lib/cassandra/data/s" +
            "ystem/compactions_in_progress-55080ab05d9c388690a4acb25fe1f77b/system-compaction" +
            "s_in_progress-tmp-ka-90592-Data.db (0.000KiB) for commitlog position ReplayPosit" +
            "ion(segmentId=1483996065722, position=19853243)\",\r\n\t\t\t    \r\n\t\t\t    \"INFO  [SlabP" +
            "oolCleaner] 2017-01-16 13:51:50,636  ColumnFamilyStore.java:1211 - Flushing larg" +
            "est CFS(Keyspace=\'OpsCenter\', ColumnFamily=\'rollup_state\') to free up room. Used" +
            " total: 0.33/0.00, live: 0.33/0.00, flushing: 0.00/0.00, this: 0.14/0.14\",\r\n\t\t\t " +
            "   \"INFO  [SlabPoolCleaner] 2017-01-16 13:51:50,636  ColumnFamilyStore.java:905 " +
            "- Enqueuing flush of rollup_state: 221288084 (14%) on-heap, 0 (0%) off-heap\",\r\n\t" +
            "\t\t    \"INFO  [MemtableFlushWriter:8021] 2017-01-16 13:51:50,637  Memtable.java:3" +
            "47 - Writing Memtable-rollup_state@1750499154(8.948MiB serialized bytes, 3237264" +
            " ops, 14%/0% of on/off-heap limit)\",\r\n\t\t\t    \"INFO  [MemtableFlushWriter:8021] 2" +
            "017-01-16 13:51:51,353  Memtable.java:382 - Completed flushing /var/lib/cassandr" +
            "a/data/OpsCenter/rollup_state-9b934af0746111e68dd04f228b4be406/OpsCenter-rollup_" +
            "state-tmp-ka-7811-Data.db (1.797MiB) for commitlog position ReplayPosition(segme" +
            "ntId=1483996065725, position=29889014)\",\r\n\t\t\t    \r\n\t\t\t    \"INFO  [BatchlogTasks:" +
            "1] 2017-01-16 13:35:06,379  ColumnFamilyStore.java:905 - Enqueuing flush of batc" +
            "hlog: 213016 (0%) on-heap, 0 (0%) off-heap\",\r\n\t\t\t    \"INFO  [MemtableFlushWriter" +
            ":8011] 2017-01-16 13:35:06,379  Memtable.java:347 - Writing Memtable-batchlog@17" +
            "63876046(112.479KiB serialized bytes, 775 ops, 0%/0% of on/off-heap limit)\",\r\n\t\t" +
            "\t    \"INFO  [MemtableFlushWriter:8011] 2017-01-16 13:35:06,380  Memtable.java:39" +
            "3 - Completed flushing /var/lib/cassandra/data/system/batchlog-0290003c977e397ca" +
            "c3efdfdc01d626b/system-batchlog-tmp-ka-10184-Data.db; nothing needed to be retai" +
            "ned.  Commitlog position was ReplayPosition(segmentId=1483996065722, position=32" +
            "855484)\",\r\n\t\t\t    \"Enqueuing flush of Memtable-user_ids.user_ids_gid@1844633142(" +
            "189/1890 serialized/live bytes, 7 ops)\"\r\n\t\t\t  ]\r\n\t\t},\r\n\t{\"MatchVersion\":null,\r\n\t" +
            "\t\t\"LevelMatch\":{\"RegExStrings\":[\"INFO\"]},\r\n\t\t\t\"ThreadIdMatch\":null,\r\n\t\t\t\"FileNam" +
            "eMatch\":{\"RegExStrings\":[\"^Memtable.java$\"]},\r\n\t\t\t\"FileLineMatch\":{\"RegExStrings" +
            "\":[\"^347$\"]},,\r\n\t\t\t\"MessageMatch\":{\"RegExStrings\":[\"^Writing\\\\s+Memtable\\\\s\"]},\r" +
            "\n\t\t\t\"ParseMessage\":{\"RegExStrings\":[\"^Writing\\\\s+Memtable-\\\\s*(?<DDLITEMNAME>[a-" +
            "z0-9\'\\\\-_$%+=!?<>^*&@]+)@\\\\d+\\\\((?<serializedheap>[0-9.]+\\\\s*\\\\w+)\\\\s+serialized" +
            "\\\\s+bytes,\\\\s+(?<operationspersec_ops>\\\\d+)\\\\s+ops,\\\\s+(?<onheapthresholdpercent" +
            ">\\\\d+\\\\%)\\\\s*/\\\\s*(?<offheapthresholdpercent>\\\\d+\\\\%)\\\\s\"]},\r\n\t\t\t\"ParseThreadId\"" +
            ":null,\r\n\t\t\t\"EventType\":\"SessionItem\",\r\n\t\t\t\"EventClass\":\"MemtableFlush\",\r\n\t\t\t\"Sub" +
            "Class\":null,\r\n\t\t\t\"Product\":\"Cassandra\",\r\n\t\t\t\"SessionKey\":\"DDLITEMNAME\",\r\n\t\t\t\"Exa" +
            "mples\":[\"INFO  [ValidationExecutor:800] 2017-01-16 13:34:06,722  ColumnFamilySto" +
            "re.java:905 - Enqueuing flush of push_device: 2202847 (0%) on-heap, 0 (0%) off-h" +
            "eap\",\r\n\t\t\t\t    \"=> INFO  [MemtableFlushWriter:8011] 2017-01-16 13:34:06,722  Mem" +
            "table.java:347 - Writing Memtable-push_device@1288484782(622.872KiB serialized b" +
            "ytes, 10486 ops, 0%/0% of on/off-heap limit)\",\r\n\t\t\t\t    \"INFO  [MemtableFlushWri" +
            "ter:8011] 2017-01-16 13:34:06,762  Memtable.java:382 - Completed flushing /var/l" +
            "ib/cassandra/data/push/push_device-109860416f0511e6aeacd54e2d191f81/push-push_de" +
            "vice-tmp-ka-278155-Data.db (147.118KiB) for commitlog position ReplayPosition(se" +
            "gmentId=1483996065722, position=19434795)\",\r\n\t\t\t\t    \r\n\t\t\t\t    \"INFO  [AntiEntro" +
            "pyStage:1] 2017-01-16 13:34:17,620  ColumnFamilyStore.java:905 - Enqueuing flush" +
            " of push_device: 264396 (0%) on-heap, 0 (0%) off-heap\",\r\n\t\t\t\t    \"INFO  [Memtabl" +
            "eFlushWriter:8011] 2017-01-16 13:34:17,621  Memtable.java:347 - Writing Memtable" +
            "-push_device@1330163944(63.895KiB serialized bytes, 1327 ops, 0%/0% of on/off-he" +
            "ap limit)\",\r\n\t\t\t\t    \"INFO  [MemtableFlushWriter:8011] 2017-01-16 13:34:17,628  " +
            "Memtable.java:382 - Completed flushing /var/lib/cassandra/data/push/push_device-" +
            "109860416f0511e6aeacd54e2d191f81/push-push_device-tmp-ka-278156-Data.db (16.152K" +
            "iB) for commitlog position ReplayPosition(segmentId=1483996065722, position=1984" +
            "5421)\",\r\n\t\t\t\t    \r\n\t\t\t\t    \"INFO  [STREAM-IN-/10.198.59.26] 2017-01-16 13:34:17," +
            "795  ColumnFamilyStore.java:905 - Enqueuing flush of push_device: 7762 (0%) on-h" +
            "eap, 0 (0%) off-heap\",\r\n\t\t\t\t    \"INFO  [MemtableFlushWriter:8012] 2017-01-16 13:" +
            "34:17,796  Memtable.java:347 - Writing Memtable-push_device@1956470048(2.617KiB " +
            "serialized bytes, 22 ops, 0%/0% of on/off-heap limit)\",\r\n\t\t\t\t    \"INFO  [Memtabl" +
            "eFlushWriter:8012] 2017-01-16 13:34:17,797  Memtable.java:382 - Completed flushi" +
            "ng /var/lib/cassandra/data/push/push_device-109860416f0511e6aeacd54e2d191f81/pus" +
            "h-push_device-tmp-ka-278157-Data.db (0.000KiB) for commitlog position ReplayPosi" +
            "tion(segmentId=1483996065722, position=19852124)\",\r\n\t\t\t\t    \r\n\t\t\t\t    \"INFO  [Co" +
            "mpactionExecutor:3211] 2017-01-16 13:34:17,817  ColumnFamilyStore.java:905 - Enq" +
            "ueuing flush of compactions_in_progress: 1315 (0%) on-heap, 0 (0%) off-heap\",\r\n\t" +
            "\t\t\t    \"INFO  [MemtableFlushWriter:8011] 2017-01-16 13:34:17,849  Memtable.java:" +
            "347 - Writing Memtable-compactions_in_progress@1461142581(0.146KiB serialized by" +
            "tes, 9 ops, 0%/0% of on/off-heap limit)\",\r\n\t\t\t\t    \"INFO  [MemtableFlushWriter:8" +
            "011] 2017-01-16 13:34:17,850  Memtable.java:382 - Completed flushing /var/lib/ca" +
            "ssandra/data/system/compactions_in_progress-55080ab05d9c388690a4acb25fe1f77b/sys" +
            "tem-compactions_in_progress-tmp-ka-90592-Data.db (0.000KiB) for commitlog positi" +
            "on ReplayPosition(segmentId=1483996065722, position=19853243)\",\r\n\t\t\t\t    \r\n\t\t\t\t " +
            "   \"INFO  [SlabPoolCleaner] 2017-01-16 13:51:50,636  ColumnFamilyStore.java:1211" +
            " - Flushing largest CFS(Keyspace=\'OpsCenter\', ColumnFamily=\'rollup_state\') to fr" +
            "ee up room. Used total: 0.33/0.00, live: 0.33/0.00, flushing: 0.00/0.00, this: 0" +
            ".14/0.14\",\r\n\t\t\t\t    \"INFO  [SlabPoolCleaner] 2017-01-16 13:51:50,636  ColumnFami" +
            "lyStore.java:905 - Enqueuing flush of rollup_state: 221288084 (14%) on-heap, 0 (" +
            "0%) off-heap\",\r\n\t\t\t\t    \"INFO  [MemtableFlushWriter:8021] 2017-01-16 13:51:50,63" +
            "7  Memtable.java:347 - Writing Memtable-rollup_state@1750499154(8.948MiB seriali" +
            "zed bytes, 3237264 ops, 14%/0% of on/off-heap limit)\",\r\n\t\t\t\t    \"INFO  [Memtable" +
            "FlushWriter:8021] 2017-01-16 13:51:51,353  Memtable.java:382 - Completed flushin" +
            "g /var/lib/cassandra/data/OpsCenter/rollup_state-9b934af0746111e68dd04f228b4be40" +
            "6/OpsCenter-rollup_state-tmp-ka-7811-Data.db (1.797MiB) for commitlog position R" +
            "eplayPosition(segmentId=1483996065725, position=29889014)\",\r\n\t\t\t\t    \r\n\t\t\t\t    \"" +
            "INFO  [BatchlogTasks:1] 2017-01-16 13:35:06,379  ColumnFamilyStore.java:905 - En" +
            "queuing flush of batchlog: 213016 (0%) on-heap, 0 (0%) off-heap\",\r\n\t\t\t\t    \"INFO" +
            "  [MemtableFlushWriter:8011] 2017-01-16 13:35:06,379  Memtable.java:347 - Writin" +
            "g Memtable-batchlog@1763876046(112.479KiB serialized bytes, 775 ops, 0%/0% of on" +
            "/off-heap limit)\",\r\n\t\t\t\t    \"INFO  [MemtableFlushWriter:8011] 2017-01-16 13:35:0" +
            "6,380  Memtable.java:393 - Completed flushing /var/lib/cassandra/data/system/bat" +
            "chlog-0290003c977e397cac3efdfdc01d626b/system-batchlog-tmp-ka-10184-Data.db; not" +
            "hing needed to be retained.  Commitlog position was ReplayPosition(segmentId=148" +
            "3996065722, position=32855484)\",\r\n\t\t\t\t    \"Enqueuing flush of Memtable-user_ids." +
            "user_ids_gid@1844633142(189/1890 serialized/live bytes, 7 ops)\"\r\n\t\t\t\t  ]\r\n\t\t},\r\n" +
            "\t\t{\"MatchVersion\":null,\r\n\t\t\t\"LevelMatch\":{\"RegExStrings\":[\"INFO\"]},\r\n\t\t\t\"ThreadI" +
            "dMatch\":null,\r\n\t\t\t\"FileNameMatch\":{\"RegExStrings\":[\"^Memtable.java$\"]},\r\n\t\t\t\"Fil" +
            "eLineMatch\":{\"RegExStrings\":[\"^382$\"]},,\r\n\t\t\t\"MessageMatch\":{\"RegExStrings\":[\"^C" +
            "ompleted\\\\s+flushing\\\\s\"]},\r\n\t\t\t\"ParseMessage\":{\"RegExStrings\":[\"^Completed\\\\s+f" +
            "lushing\\\\s+(?<SSTABLEPATH>[^ ]+)\\\\s+\\\\((?<flushedstorage>[0-9.]+\\\\s*\\\\w+)\\\\)\\\\s+" +
            "for\\\\s+.+\\\\(segmentId\\\\s*=\\\\s*(?<replaysegmentid>\\\\d+)\\\\s*,\\\\s+position\\\\s*=\\\\s*" +
            "(?<replayposition>\\\\d+)\\\\)$\"]},\r\n\t\t\t\"ParseThreadId\":null,\r\n\t\t\t\"EventType\":\"Sessi" +
            "onEnd\",\r\n\t\t\t\"EventClass\":\"MemtableFlush\",\r\n\t\t\t\"SubClass\":null,\r\n\t\t\t\"Product\":\"Ca" +
            "ssandra\",\r\n\t\t\t\"SessionKey\":\"SSTABLEPATH=>DDLITEMNAME\",\r\n\t\t\t\"Examples\":[\"INFO  [V" +
            "alidationExecutor:800] 2017-01-16 13:34:06,722  ColumnFamilyStore.java:905 - Enq" +
            "ueuing flush of push_device: 2202847 (0%) on-heap, 0 (0%) off-heap\",\r\n\t\t\t\t    \"I" +
            "NFO  [MemtableFlushWriter:8011] 2017-01-16 13:34:06,722  Memtable.java:347 - Wri" +
            "ting Memtable-push_device@1288484782(622.872KiB serialized bytes, 10486 ops, 0%/" +
            "0% of on/off-heap limit)\",\r\n\t\t\t\t    \"=> INFO  [MemtableFlushWriter:8011] 2017-01" +
            "-16 13:34:06,762  Memtable.java:382 - Completed flushing /var/lib/cassandra/data" +
            "/push/push_device-109860416f0511e6aeacd54e2d191f81/push-push_device-tmp-ka-27815" +
            "5-Data.db (147.118KiB) for commitlog position ReplayPosition(segmentId=148399606" +
            "5722, position=19434795)\",\r\n\r\n\t\t\t\t    \"INFO  [AntiEntropyStage:1] 2017-01-16 13:" +
            "34:17,620  ColumnFamilyStore.java:905 - Enqueuing flush of push_device: 264396 (" +
            "0%) on-heap, 0 (0%) off-heap\",\r\n\t\t\t\t    \"INFO  [MemtableFlushWriter:8011] 2017-0" +
            "1-16 13:34:17,621  Memtable.java:347 - Writing Memtable-push_device@1330163944(6" +
            "3.895KiB serialized bytes, 1327 ops, 0%/0% of on/off-heap limit)\",\r\n\t\t\t\t    \"INF" +
            "O  [MemtableFlushWriter:8011] 2017-01-16 13:34:17,628  Memtable.java:382 - Compl" +
            "eted flushing /var/lib/cassandra/data/push/push_device-109860416f0511e6aeacd54e2" +
            "d191f81/push-push_device-tmp-ka-278156-Data.db (16.152KiB) for commitlog positio" +
            "n ReplayPosition(segmentId=1483996065722, position=19845421)\",\r\n\r\n\t\t\t\t    \"INFO " +
            " [STREAM-IN-/10.198.59.26] 2017-01-16 13:34:17,795  ColumnFamilyStore.java:905 -" +
            " Enqueuing flush of push_device: 7762 (0%) on-heap, 0 (0%) off-heap\",\r\n\t\t\t\t    \"" +
            "INFO  [MemtableFlushWriter:8012] 2017-01-16 13:34:17,796  Memtable.java:347 - Wr" +
            "iting Memtable-push_device@1956470048(2.617KiB serialized bytes, 22 ops, 0%/0% o" +
            "f on/off-heap limit)\",\r\n\t\t\t\t    \"INFO  [MemtableFlushWriter:8012] 2017-01-16 13:" +
            "34:17,797  Memtable.java:382 - Completed flushing /var/lib/cassandra/data/push/p" +
            "ush_device-109860416f0511e6aeacd54e2d191f81/push-push_device-tmp-ka-278157-Data." +
            "db (0.000KiB) for commitlog position ReplayPosition(segmentId=1483996065722, pos" +
            "ition=19852124)\",\r\n\r\n\t\t\t\t    \"INFO  [CompactionExecutor:3211] 2017-01-16 13:34:1" +
            "7,817  ColumnFamilyStore.java:905 - Enqueuing flush of compactions_in_progress: " +
            "1315 (0%) on-heap, 0 (0%) off-heap\",\r\n\t\t\t\t    \"INFO  [MemtableFlushWriter:8011] " +
            "2017-01-16 13:34:17,849  Memtable.java:347 - Writing Memtable-compactions_in_pro" +
            "gress@1461142581(0.146KiB serialized bytes, 9 ops, 0%/0% of on/off-heap limit)\"," +
            "\r\n\t\t\t\t    \"INFO  [MemtableFlushWriter:8011] 2017-01-16 13:34:17,850  Memtable.ja" +
            "va:382 - Completed flushing /var/lib/cassandra/data/system/compactions_in_progre" +
            "ss-55080ab05d9c388690a4acb25fe1f77b/system-compactions_in_progress-tmp-ka-90592-" +
            "Data.db (0.000KiB) for commitlog position ReplayPosition(segmentId=1483996065722" +
            ", position=19853243)\",\r\n\r\n\t\t\t\t    \"INFO  [SlabPoolCleaner] 2017-01-16 13:51:50,6" +
            "36  ColumnFamilyStore.java:1211 - Flushing largest CFS(Keyspace=\'OpsCenter\', Col" +
            "umnFamily=\'rollup_state\') to free up room. Used total: 0.33/0.00, live: 0.33/0.0" +
            "0, flushing: 0.00/0.00, this: 0.14/0.14\",\r\n\t\t\t\t    \"INFO  [SlabPoolCleaner] 2017" +
            "-01-16 13:51:50,636  ColumnFamilyStore.java:905 - Enqueuing flush of rollup_stat" +
            "e: 221288084 (14%) on-heap, 0 (0%) off-heap\",\r\n\t\t\t\t    \"INFO  [MemtableFlushWrit" +
            "er:8021] 2017-01-16 13:51:50,637  Memtable.java:347 - Writing Memtable-rollup_st" +
            "ate@1750499154(8.948MiB serialized bytes, 3237264 ops, 14%/0% of on/off-heap lim" +
            "it)\",\r\n\t\t\t\t    \"INFO  [MemtableFlushWriter:8021] 2017-01-16 13:51:51,353  Memtab" +
            "le.java:382 - Completed flushing /var/lib/cassandra/data/OpsCenter/rollup_state-" +
            "9b934af0746111e68dd04f228b4be406/OpsCenter-rollup_state-tmp-ka-7811-Data.db (1.7" +
            "97MiB) for commitlog position ReplayPosition(segmentId=1483996065725, position=2" +
            "9889014)\",\r\n\r\n\t\t\t\t    \"INFO  [BatchlogTasks:1] 2017-01-16 13:35:06,379  ColumnFa" +
            "milyStore.java:905 - Enqueuing flush of batchlog: 213016 (0%) on-heap, 0 (0%) of" +
            "f-heap\",\r\n\t\t\t\t    \"INFO  [MemtableFlushWriter:8011] 2017-01-16 13:35:06,379  Mem" +
            "table.java:347 - Writing Memtable-batchlog@1763876046(112.479KiB serialized byte" +
            "s, 775 ops, 0%/0% of on/off-heap limit)\",\r\n\t\t\t\t    \"INFO  [MemtableFlushWriter:8" +
            "011] 2017-01-16 13:35:06,380  Memtable.java:393 - Completed flushing /var/lib/ca" +
            "ssandra/data/system/batchlog-0290003c977e397cac3efdfdc01d626b/system-batchlog-tm" +
            "p-ka-10184-Data.db; nothing needed to be retained.  Commitlog position was Repla" +
            "yPosition(segmentId=1483996065722, position=32855484)\",\r\n\t\t\t\t    \"Enqueuing flus" +
            "h of Memtable-user_ids.user_ids_gid@1844633142(189/1890 serialized/live bytes, 7" +
            " ops)\"\r\n\t\t\t\t  ]\r\n\t\t}\t\r\n]}")]
        public string Log4NetParser {
            get {
                return ((string)(this["Log4NetParser"]));
            }
        }
    }
}
