//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSEDiagtnosticToExcel.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".xlsx")]
        public string ExcelFileExtension {
            get {
                return ((string)(this["ExcelFileExtension"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{\r\n\"CFStats\":{\"Column\":\"F\",\"Attrs\":[\r\n\t\"Average live cells per slice (last five m" +
            "inutes)\",\r\n\t\"Average tombstones per slice (last five minutes)\",\r\n\t\"Batch size ma" +
            "ximum\",\r\n\t\"Batch size mean\",\r\n\t\"Batch size minimum\",\r\n\t\"Batch size occurrences\"," +
            "\r\n\t\"Bloom filter false positives\",\r\n\t\"Bloom filter false ratio\",\r\n\t\"Bloom filter" +
            " off heap memory used\",\r\n\t\"Bloom filter space used\",\r\n\t\"Compacted partition maxi" +
            "mum bytes\",\r\n\t\"Compacted partition mean bytes\",\r\n\t\"Compacted partition minimum b" +
            "ytes\",\r\n\t\"Compaction maximum latency\",\r\n\t\"Compaction maximum rate\",\r\n\t\"Compactio" +
            "n mean latency\",\r\n\t\"Compaction mean rate\",\r\n\t\"Compaction mean rate\",\r\n\t\"Compacti" +
            "on minimum latency\",\r\n\t\"Compaction minimum rate\",\r\n\t\"Compaction occurrences\",\r\n\t" +
            "\"Compression metadata off heap memory used\",\r\n\t\"Index summary off heap memory us" +
            "ed\",\r\n\t\"Local read count\",\r\n\t\"Local read latency\",\r\n\t\"Local write count\",\r\n\t\"Loc" +
            "al write latency\",\r\n\t\"Maximum live cells per slice (last five minutes)\",\r\n\t\"Maxi" +
            "mum tombstones per slice (last five minutes)\",\r\n\t\"MemTable OPS maximum\",\r\n\t\"MemT" +
            "able OPS mean\",\r\n\t\"MemTable OPS minimum\",\r\n\t\"MemTable Size maximum\",\r\n\t\"MemTable" +
            " Size mean\",\r\n\t\"MemTable Size minimum\",\r\n\t\"MemTable occurrences\",\r\n\t\"Memtable ce" +
            "ll count\",\r\n\t\"Memtable data size\",\r\n\t\"Memtable off heap memory used\",\r\n\t\"Memtabl" +
            "e switch count\",\r\n\t\"Number of keys (estimate)\",\r\n\t\"Off heap memory used (total)\"" +
            ",\r\n\t\"Partition large maximum\",\r\n\t\"Partition large mean\",\r\n\t\"Partition large mini" +
            "mum\",\r\n\t\"Partition large occurrences\",\r\n\t\"Pending flushes\",\r\n\t\"Read Count\",\r\n\t\"R" +
            "ead latency\",\r\n\t\"Read latency maximum\",\r\n\t\"SSTable Compression Ratio\",\r\n\t\"SSTabl" +
            "e count\",\r\n\t\"SSTable read maximum \",\r\n\t\"Space used (live)\",\r\n\t\"Space used (total" +
            ")\",\r\n\t\"Space used by snapshots (total)\",\r\n\t\"Tombstones warning Total\",\r\n\t\"Tombst" +
            "ones warning maximum\",\r\n\t\"Tombstones warning mean\",\r\n\t\"Tombstones warning minimu" +
            "m\",\r\n\t\"Tombstones warning occurrences\",\r\n\t\"Write Count\",\r\n\t\"Write latency\",\r\n\t\"W" +
            "rite latency maximum\",\r\n\t\"Unlogged Batch Partitions Count Total\",\r\n\t\"Unlogged Ba" +
            "tch Partitions Count maximum\",\r\n\t\"Unlogged Batch Partitions Count mean\",\r\n\t\"Unlo" +
            "gged Batch Partitions Count minimum\",\r\n\t\"Unlogged Batch Partitions Count occurre" +
            "nces\",\r\n\t\"Tombstones query aborted Total\",\r\n\t\"Tombstones query aborted maximum\"," +
            "\r\n\t\"Tombstones query aborted mean\",\r\n\t\"Tombstones query aborted minimum\",\r\n\t\"Tom" +
            "bstones query aborted occurences\",\r\n\t\"Read Repair maximum latency\",\r\n\t\"Read Repa" +
            "ir minimum latency\",\r\n\t\"Read Repair mean latency\",\r\n\t\"Read Repair occurrences\",\r" +
            "\n\t\"Read Repair Aborted occurrences\",\r\n\t\"Solr reindex duration maximum\",\r\n\t\"Solr " +
            "reindex duration minimum\",\r\n\t\"Solr reindex duration mean\",\r\n\t\"Solr reindex durat" +
            "ion stdev\",\r\n\t\"Solr reindex occurrences\",\r\n\t\"AntiCompaction maximum latency\",\r\n\t" +
            "\"AntiCompaction mean latency\",\r\n\t\"AntiCompaction minimum latency\",\r\n\t\"AntiCompac" +
            "tion occurrences\",\r\n\t\"AntiCompaction SSTable count\",\r\n\t\"Memtable Flush maximum l" +
            "atency\",\r\n\t\"Memtable Flush mean latency\",\r\n\t\"Memtable Flush minimum latency\",\r\n\t" +
            "\"Memtable Flush occurrences\",\r\n\t\"Memtable Flush maximum IORate\",\r\n\t\"Memtable Flu" +
            "sh mean IORate\",\r\n\t\"Memtable Flush minimum IORate\",\r\n\t\"Memtable Flush maximum St" +
            "orage\",\r\n\t\"Memtable Flush mean Storage\",\r\n\t\"Memtable Flush minimum Storage\",\r\n\t\"" +
            "Memtable Flush total Storage\",\r\n                   \"Error (DC Not Defined within" +
            " KS)\",\r\n                   \"Errors\"\r\n]},\r\n\"NodeStats\":{\"Column\":\"D\",\"Attrs\":[\r\n\t" +
            "\"AntiEntropySessions\",\r\n\t\"AntiEntropyStage\",\r\n\t\"AntiEntropyStage Total\",\r\n\t\"Anti" +
            "EntropyStage maximum\",\r\n\t\"AntiEntropyStage mean\",\r\n\t\"AntiEntropyStage minimum\",\r" +
            "\n\t\"AntiEntropyStage occurrences\",\r\n\t\"BINARY\",\r\n\t\"COUNTER_MUTATION\",\r\n\t\"CacheClea" +
            "nupExecutor\",\r\n\t\"CommitLogArchiver\",\r\n\t\"CompactionExecutor\",\r\n\t\"CompactionExecut" +
            "or Total\",\r\n\t\"CompactionExecutor maximum\",\r\n\t\"CompactionExecutor mean\",\r\n\t\"Compa" +
            "ctionExecutor minimum\",\r\n\t\"CompactionExecutor occurrences\",\r\n\t\"CounterMutationSt" +
            "age\",\r\n\t\"CounterMutationStage Total\",\r\n\t\"CounterMutationStage maximum\",\r\n\t\"Count" +
            "erMutationStage mean\",\r\n\t\"CounterMutationStage minimum\",\r\n\t\"CounterMutationStage" +
            " occurrences\",\r\n\t\"GC maximum latency\",\r\n\t\"GC mean latency\",\r\n\t\"GC minimum latenc" +
            "y\",\r\n\t\"GC occurrences\",\r\n\t\"GossipStage\",\r\n\t\"GossipStage Total\",\r\n\t\"GossipStage m" +
            "aximum\",\r\n\t\"GossipStage mean\",\r\n\t\"GossipStage minimum\",\r\n\t\"GossipStage occurrenc" +
            "es\",\r\n\t\"HintedHandoff\",\r\n\t\"HintedHandoff Total\",\r\n\t\"HintedHandoff maximum\",\r\n\t\"H" +
            "intedHandoff mean\",\r\n\t\"HintedHandoff minimum\",\r\n\t\"HintedHandoff occurrences\",\r\n\t" +
            "\"InternalResponseStage\",\r\n\t\"InternalResponseStage Total\",\r\n\t\"InternalResponseSta" +
            "ge maximum\",\r\n\t\"InternalResponseStage mean\",\r\n\t\"InternalResponseStage minimum\",\r" +
            "\n\t\"InternalResponseStage occurrences\",\r\n\t\"MUTATION\",\r\n\t\"MemtableFlushWriter\",\r\n\t" +
            "\"MemtableFlushWriter Total\",\r\n\t\"MemtableFlushWriter maximum\",\r\n\t\"MemtableFlushWr" +
            "iter mean\",\r\n\t\"MemtableFlushWriter minimum\",\r\n\t\"MemtableFlushWriter occurrences\"" +
            ",\r\n\t\"MemtablePostFlush\",\r\n\t\"MemtablePostFlush Total\",\r\n\t\"MemtablePostFlush maxim" +
            "um\",\r\n\t\"MemtablePostFlush mean\",\r\n\t\"MemtablePostFlush minimum\",\r\n\t\"MemtablePostF" +
            "lush occurrences\",\r\n\t\"MemtableReclaimMemory\",\r\n\t\"MemtableReclaimMemory Total\",\r\n" +
            "\t\"MemtableReclaimMemory maximum\",\r\n\t\"MemtableReclaimMemory mean\",\r\n\t\"MemtableRec" +
            "laimMemory minimum\",\r\n\t\"MemtableReclaimMemory occurrences\",\r\n\t\"MigrationStage\",\r" +
            "\n\t\"MigrationStage Total\",\r\n\t\"MigrationStage maximum\",\r\n\t\"MigrationStage mean\",\r\n" +
            "\t\"MigrationStage minimum\",\r\n\t\"MigrationStage occurrences\",\r\n\t\"MiscStage\",\r\n\t\"Mut" +
            "ationStage\",\r\n\t\"MutationStage Total\",\r\n\t\"MutationStage maximum\",\r\n\t\"MutationStag" +
            "e mean\",\r\n\t\"MutationStage minimum\",\r\n\t\"MutationStage occurrences\",\r\n\t\"PAGED_RANG" +
            "E\",\r\n\t\"Pause maximum latency\",\r\n\t\"Pause mean latency\",\r\n\t\"Pause minimum latency\"" +
            ",\r\n\t\"Pause occurrences\",\r\n\t\"PendingRangeCalculator\",\r\n\t\"PendingRangeCalculator T" +
            "otal\",\r\n\t\"PendingRangeCalculator maximum\",\r\n\t\"PendingRangeCalculator mean\",\r\n\t\"P" +
            "endingRangeCalculator minimum\",\r\n\t\"PendingRangeCalculator occurrences\",\r\n\t\"RANGE" +
            "_SLICE\",\r\n\t\"READ\",\r\n\t\"READ_REPAIR\",\r\n\t\"REQUEST_RESPONSE\",\r\n\t\"ReadRepairStage\",\r\n" +
            "\t\"ReadRepairStage Total\",\r\n\t\"ReadRepairStage maximum\",\r\n\t\"ReadRepairStage mean\"," +
            "\r\n\t\"ReadRepairStage minimum\",\r\n\t\"ReadRepairStage occurrences\",\r\n\t\"ReadStage\",\r\n\t" +
            "\"ReadStage Total\",\r\n\t\"ReadStage maximum\",\r\n\t\"ReadStage mean\",\r\n\t\"ReadStage minim" +
            "um\",\r\n\t\"ReadStage occurrences\",\r\n\t\"RequestResponseStage\",\r\n\t\"RequestResponseStag" +
            "e Total\",\r\n\t\"RequestResponseStage maximum\",\r\n\t\"RequestResponseStage mean\",\r\n\t\"Re" +
            "questResponseStage minimum\",\r\n\t\"RequestResponseStage occurrences\",\r\n\t\"Sampler\",\r" +
            "\n\t\"Slow Query maximum latency\",\r\n\t\"Slow Query mean latency\",\r\n\t\"Slow Query minim" +
            "um latency\",\r\n\t\"Slow Query occurrences\",\r\n\t\"ValidationExecutor\",\r\n\t\"_TRACE\",\r\n\t\"" +
            "OutOfMemoryError occurrences\",\r\n\t\"CommitLogFlushFailure occurrences\",\r\n\t\"Dropped" +
            " Hints Total\",\r\n\t\"Dropped Hints maximum\",\r\n\t\"Dropped Hints mean\",\r\n\t\"Dropped Hin" +
            "ts minimum\",\r\n\t\"Dropped Hints occurrences\",\r\n\t\"Allocation Failed Maximum Memory " +
            "Reached Total\",\r\n\t\"Allocation Failed Maximum Memory Reached maximum\",\r\n\t\"Allocat" +
            "ion Failed Maximum Memory Reached minimum\",\r\n\t\"Allocation Failed Maximum Memory " +
            "Reached mean\",\r\n\t\"Allocation Failed Maximum Memory Reached occurrences\",\r\n\t\"Drop" +
            "ped Mutation Total\",\r\n\t\"Dropped Mutation maximum\",\r\n\t\"Dropped Mutation mean\",\r\n\t" +
            "\"Dropped Mutation minimum\",\r\n\t\"Dropped Mutation occurrences\",\r\n\t\"GC Continuous m" +
            "aximum latency\",\r\n\t\"GC Continuous minimum latency\",\r\n\t\"GC Continuous mean latenc" +
            "y\",\r\n\t\"GC Continuous occurrences\",\r\n\t\"GC Continuous latency\",\r\n\t\"GC Continuous s" +
            "tandard deviation latency\",\r\n\t\"GC TimeFrame maximum latency\",\r\n\t\"GC TimeFrame mi" +
            "nimum latency\",\r\n\t\"GC TimeFrame mean latency\",\r\n\t\"GC TimeFrame occurrences\",\r\n\t\"" +
            "GC TimeFrame latency\",\r\n\t\"GC TimeFrame standard deviation latency\",\r\n\t\"GC TimeFr" +
            "ame percent\",\r\n\t\"Timedout Hints Total\",\r\n\t\"Timedout Hints maximum\",\r\n\t\"Timedout " +
            "Hints mean\",\r\n\t\"Timedout Hints minimum\",\r\n\t\"Timedout Hints occurrences\",\r\n\t\"Conc" +
            "urrent Compaction maximum\",\r\n\t\"Concurrent Compaction minimum\",\r\n\t\"Concurrent Com" +
            "paction mean\",\r\n\t\"Concurrent Compaction standard deviation\",\r\n\t\"Concurrent Compa" +
            "ction Total\",\r\n\t\"Concurrent Compaction occurrences\",\r\n\t\"Concurrent MemtableFlush" +
            " maximum\",\r\n\t\"Concurrent MemtableFlush minimum\",\r\n\t\"Concurrent MemtableFlush mea" +
            "n\",\r\n\t\"Concurrent MemtableFlush standard deviation\",\r\n\t\"Concurrent MemtableFlush" +
            " Total\",\r\n\t\"Concurrent MemtableFlush occurrences\",\r\n\t\"Concurrent Compaction/Flus" +
            "h Performance Warnings maximum\",\r\n\t\"Concurrent Compaction/Flush Performance Warn" +
            "ings minimum\",\r\n\t\"Concurrent Compaction/Flush Performance Warnings mean\",\r\n\t\"Con" +
            "current Compaction/Flush Performance Warnings standard deviation\",\r\n\t\"Concurrent" +
            " Compaction/Flush GC maximum\",\r\n\t\"Concurrent Compaction/Flush GC minimum\",\r\n\t\"Co" +
            "ncurrent Compaction/Flush GC mean\",\r\n\t\"Concurrent Compaction/Flush GC standard d" +
            "eviation\",\r\n\t\"Shard State Change Schema\",\r\n\t\"Shard State Change Dead Node\",\r\n\t\"N" +
            "ode Marked Down (Dropped Hints)\",\r\n\t\"Node Not Responding (Timed Out Hints)\"\r\n]}\r" +
            "\n\r\n}")]
        public string WorkSheetDefaultAttrs {
            get {
                return ((string)(this["WorkSheetDefaultAttrs"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AppendToWorkSheet {
            get {
                return ((bool)(this["AppendToWorkSheet"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[>=32] 0.00 \"days\";[<1]  [hh]:mm;d hh:mm")]
        public string ExcelTimeSpanFormat {
            get {
                return ((string)(this["ExcelTimeSpanFormat"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("mm/dd/yyyy hh:mm:ss.000")]
        public string ExcelDateTimeFormat {
            get {
                return ((string)(this["ExcelDateTimeFormat"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[hh]:mm")]
        public string ExcelTimeFormat {
            get {
                return ((string)(this["ExcelTimeFormat"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ExcelPackageCache {
            get {
                return ((bool)(this["ExcelPackageCache"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ExcelSaveWorkSheet {
            get {
                return ((bool)(this["ExcelSaveWorkSheet"]));
            }
        }
    }
}
