VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "WSFilterData"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Public Active As Boolean
Public WSName As String
Public PTName As String
Public FldName As String
Public pvtFldType As String
Public StaticFilterValue As String
Public SetFilterValue As String
Public LblType As String
Public LblValue1 As String
Public LblValue2 As String
Public ValType As String
Public ValValue1 As String
Public ValValue2 As String


