//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSEDiagnosticAnalytics.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public double LogFileInfoAnalysisContinousEventInDays {
            get {
                return ((double)(this["LogFileInfoAnalysisContinousEventInDays"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public double LogFileInfoAnalysisGapTriggerInMins {
            get {
                return ((double)(this["LogFileInfoAnalysisGapTriggerInMins"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@".\AggregateGroups.json,.\Json\AggregateGroups.json,[cpld]\Json\AggregateGroups.json,[cpld]\AggregateGroups.json,[ApplicationRunTimeDirectory]\Json\AggregateGroups.json,[ApplicationRunTimeDirectory]\AggregateGroups.json,.\Json\AggregateGroups.json,.\AggregateGroups.json")]
        public string AggregateGroups {
            get {
                return ((string)(this["AggregateGroups"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:05:00")]
        public global::System.TimeSpan GCTimeFrameDetection {
            get {
                return ((global::System.TimeSpan)(this["GCTimeFrameDetection"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150")]
        public double GCBackToBackToleranceMS {
            get {
                return ((double)(this["GCBackToBackToleranceMS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.25")]
        public double GCTimeFrameDetectionThreholdMin {
            get {
                return ((double)(this["GCTimeFrameDetectionThreholdMin"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:30:00")]
        public global::System.TimeSpan LogAggregationPeriod {
            get {
                return ((global::System.TimeSpan)(this["LogAggregationPeriod"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5000")]
        public int LogAggregationNodeStatMbrLimit {
            get {
                return ((int)(this["LogAggregationNodeStatMbrLimit"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.02")]
        public decimal LogAggregationNodeStatMbrLimitTakeNItemsPercent {
            get {
                return ((decimal)(this["LogAggregationNodeStatMbrLimitTakeNItemsPercent"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[\r\n{\"AttrName\":\"Local read latency\",\r\n \"MinTrigger\":0.65,\r\n \"AttrValue\":{\"Type\":T" +
            "ypes.Normal,\r\n \t\t\"CalcType\":CalcTypes.Normal,\r\n  \t\t\"Threshold\":1.5,\r\n  \t\t\"Weight" +
            "\":1.0,\r\n  \t\t\"WeightFactor\":1.0,\r\n  \t\t\"PenaltyFactor\":0.60\r\n \t},\r\n \"MaxValue\":{\"T" +
            "ype\":Types.Max,\r\n \t\t\"CalcType\":CalcTypes.Normal,\t\r\n \t\t\"Threshold\":1.5,\r\n \t\t\"Weig" +
            "ht\":1.0,\r\n \t\t\"WeightFactor\":0.25,\r\n \t\t\"PenaltyFactor\":0.0\r\n \t},\r\n \"MinValue\":{\"T" +
            "ype\":Types.Min,\r\n \t\t\"CalcType\":CalcTypes.Normal,\r\n \t\t\"Threshold\":0.75,\r\n \t\t\"Weig" +
            "ht\":1.0,\r\n \t\t\"WeightFactor\":0.25,\r\n \t\t\"PenaltyFactor\":0.0\r\n \t},\r\n \"AvgValue\":{\"T" +
            "ype\":Types.Avg,\r\n \t\t\"CalcType\":CalcTypes.Normal,\r\n \t\t\"Threshold\":1.0,\r\n \t\t\"Weigh" +
            "t\":1.0,\r\n \t\t\"WeightFactor\":0.50,\r\n \t\t\"PenaltyFactor\":0.10\r\n \t},\r\n \"StdDevValue\":" +
            "null\r\n},\r\n{\"AttrName\":\"Local write latency\",\r\n \"MinTrigger\":0.65,\r\n \"AttrValue\":" +
            "{\"Type\":0,\r\n \t\t\"CalcType\":CalcTypes.Normal,\r\n   \t\t\"Threshold\":1.0,\r\n   \t\t\"Weight" +
            "\":1.0,\r\n   \t\t\"WeightFactor\":1.0,\r\n   \t\t\"PenaltyFactor\":0.60\r\n \t},\r\n \"MaxValue\":{" +
            "\"Type\":Types.Max,\r\n \t\t\"CalcType\":CalcTypes.Normal,\r\n \t\t\"Threshold\":1.0,\r\n \t\t\"Wei" +
            "ght\":1.0,\r\n \t\t\"WeightFactor\":0.25,\r\n \t\t\"PenaltyFactor\":0.0\r\n \t},\r\n \"MinValue\":{\"" +
            "Type\":Types.Min,\r\n \t\t\"CalcType\":CalcTypes.Normal,\r\n \t\t\"Threshold\":0.30,\r\n \t\t\"Wei" +
            "ght\":1.0,\r\n \t\t\"WeightFactor\":0.25,\r\n \t\t\"PenaltyFactor\":0.0\r\n \t},\r\n \"AvgValue\":{\"" +
            "Type\":Types.Avg,\r\n \t\t\"CalcType\":CalcTypes.Normal,\r\n \t\t\"Threshold\":0.60,\r\n \t\t\"Wei" +
            "ght\":1.0,\r\n \t\t\"WeightFactor\":0.50,\r\n \t\t\"PenaltyFactor\":0.10\r\n \t},\r\n \"StdDevValue" +
            "\":null\r\n},\r\n{\"AttrName\":\"SSTable count\",\r\n \"MinTrigger\":0.60,\r\n \"AttrValue\":{\"Ty" +
            "pe\":0,\r\n \t\t\"CalcType\":CalcTypes.Normal,\r\n   \t\t\"Threshold\":30.0,\r\n   \t\t\"Weight\":1" +
            ".0,\r\n   \t\t\"WeightFactor\":1.0,\r\n   \t\t\"PenaltyFactor\":0.60\r\n \t},\r\n \"MaxValue\":{\"Ty" +
            "pe\":Types.Max,\r\n \t\t\"CalcType\":CalcTypes.Normal,\r\n \t\t\"Threshold\":30.0,\r\n \t\t\"Weigh" +
            "t\":1.0,\r\n \t\t\"WeightFactor\":0.30,\r\n \t\t\"PenaltyFactor\":0.0\r\n \t},\r\n \"MinValue\":{\"Ty" +
            "pe\":Types.Min,\r\n \t\t\"CalcType\":CalcTypes.Normal,\r\n \t\t\"Threshold\":30.0,\r\n \t\t\"Weigh" +
            "t\":1.0,\r\n \t\t\"WeightFactor\":0.40,\r\n \t\t\"PenaltyFactor\":0.10\r\n \t},\r\n \"AvgValue\":{\"T" +
            "ype\":Types.Avg,\r\n \t\t\"CalcType\":CalcTypes.Normal,\r\n \t\t\"Threshold\":30.0,\r\n \t\t\"Weig" +
            "ht\":1.0,\r\n \t\t\"WeightFactor\":0.30,\r\n \t\t\"PenaltyFactor\":0.20\r\n \t},\r\n \"StdDevValue\"" +
            ":null\r\n},\r\n{\"AttrName\":\"Partition large\",\r\n \"MinTrigger\":0.60,\r\n \"AttrValue\":{\"T" +
            "ype\":0,\r\n \t\t\"CalcType\":CalcTypes.Normal,\r\n   \t\t\"Threshold\":100.0,\r\n   \t\t\"Weight\"" +
            ":1.0,\r\n   \t\t\"WeightFactor\":1.0,\r\n   \t\t\"PenaltyFactor\":0.60\r\n \t},\r\n \"MaxValue\":{\"" +
            "Type\":Types.Max,\r\n \t\t\"CalcType\":CalcTypes.Normal,\r\n \t\t\"Threshold\":100.0,\r\n \t\t\"We" +
            "ight\":1.0,\r\n \t\t\"WeightFactor\":0.30,\r\n \t\t\"PenaltyFactor\":0.0\r\n \t},\r\n \"MinValue\":{" +
            "\"Type\":Types.Min,\r\n \t\t\"CalcType\":CalcTypes.Normal,\r\n \t\t\"Threshold\":100.0,\r\n \t\t\"W" +
            "eight\":1.0,\r\n \t\t\"WeightFactor\":0.40,\r\n \t\t\"PenaltyFactor\":0.10\r\n \t},\r\n \"AvgValue\"" +
            ":{\"Type\":Types.Avg,\r\n \t\t\"CalcType\":CalcTypes.Normal,\r\n \t\t\"Threshold\":100.0,\r\n \t\t" +
            "\"Weight\":1.0,\r\n \t\t\"WeightFactor\":0.30,\r\n \t\t\"PenaltyFactor\":0.20\r\n \t},\r\n \"StdDevV" +
            "alue\":null\r\n},\r\n{\"AttrName\":\"Tombstone/Live Percent\",\r\n \"MinTrigger\":0.60,\r\n \"At" +
            "trValue\":{\"Type\":0,\r\n \t\t\"CalcType\":CalcTypes.Normal,\r\n   \t\t\"Threshold\":0.60,\r\n  " +
            " \t\t\"Weight\":1.0,\r\n   \t\t\"WeightFactor\":1.0,\r\n   \t\t\"PenaltyFactor\":0.60\r\n \t},\r\n \"M" +
            "axValue\":{\"Type\":Types.Max,\r\n \t\t\"CalcType\":CalcTypes.Normal,\r\n \t\t\"Threshold\":0.6" +
            "0,\r\n \t\t\"Weight\":1.0,\r\n \t\t\"WeightFactor\":0.30,\r\n \t\t\"PenaltyFactor\":0.0\r\n \t},\r\n \"M" +
            "inValue\":{\"Type\":Types.Min,\r\n \t\t\"CalcType\":CalcTypes.Normal,\r\n \t\t\"Threshold\":0.6" +
            "0,\r\n \t\t\"Weight\":1.0,\r\n \t\t\"WeightFactor\":0.40,\r\n \t\t\"PenaltyFactor\":0.10\r\n \t},\r\n \"" +
            "AvgValue\":{\"Type\":Types.Avg,\r\n \t\t\"CalcType\":CalcTypes.Normal,\r\n \t\t\"Threshold\":0." +
            "60,\r\n \t\t\"Weight\":1.0,\r\n \t\t\"WeightFactor\":0.30,\r\n \t\t\"PenaltyFactor\":0.20\r\n \t},\r\n " +
            "\"StdDevValue\":null\r\n}\r\n]")]
        public string AttributeThresholds {
            get {
                return ((string)(this["AttributeThresholds"]));
            }
        }
    }
}
