CREATE TABLE [dbo].[TaggedItems] (
	[DiagnosticId]					 VARCHAR (115) NOT NULL,
	[RowId]							 BIGINT NOT NULL,
    [Keyspace Name]                  VARCHAR (255) NULL,
    [Compaction Strategy]            VARCHAR (255) NULL,
    [Table Name]                     VARCHAR (255) NULL,
    [Data Center]                    VARCHAR (100) NULL,
    [Node IPAddress]                 VARCHAR (55) NULL,
    [CQL Type]                       VARCHAR (50) NULL,
    [Weighted Factor Max]            DECIMAL (18)  NULL,
    [Weighted Factor Avg]            DECIMAL (18)  NULL,
    [Read Max]                       DECIMAL (18)  NULL,
    [Read Min]                       DECIMAL (18)  NULL,
    [Read Avg]                       DECIMAL (18)  NULL,
    [Read StdDev]                    DECIMAL (18)  NULL,
    [Read Factor]                    DECIMAL (18)  NULL,
    [Read Percent]                   DECIMAL (18)  NULL,
    [Write Max]                      DECIMAL (18)  NULL,
    [Write Min]                      DECIMAL (18)  NULL,
    [Write Avg]                      DECIMAL (18)  NULL,
    [Write StdDev]                   DECIMAL (18)  NULL,
    [Write Factor]                   DECIMAL (18)  NULL,
    [Write Percent]                  DECIMAL (18)  NULL,
    [Keys Percent]                   DECIMAL (18)  NULL,
    [SSTables Max]                   BIGINT        NULL,
    [SSTables Min]                   BIGINT        NULL,
    [SSTables Avg]                   DECIMAL (18)  NULL,
    [SSTables StdDev]                DECIMAL (18)  NULL,
    [SSTables Factor]                DECIMAL (18)  NULL,
    [SSTable Percent]                DECIMAL (18)  NULL,
    [Storage Percent]                DECIMAL (18)  NULL,
    [Tombstone Ratio Max]            DECIMAL (18)  NULL,
    [Tombstone Ratio Min]            DECIMAL (18)  NULL,
    [Tombstone Ratio Avg]            DECIMAL (18)  NULL,
    [Tombstone Ratio StdDev]         DECIMAL (18)  NULL,
    [Tombstone Ratio Factor]         DECIMAL (18)  NULL,
    [Tombstones Read]                BIGINT        NULL,
    [Live Read]                      BIGINT        NULL,
    [Partition Size Max]             DECIMAL (18)  NULL,
    [Partition Size Min]             DECIMAL (18)  NULL,
    [Partition Size Avg]             DECIMAL (18)  NULL,
    [Partition Size StdDev]          DECIMAL (18)  NULL,
    [Partition Size Factor]          DECIMAL (18)  NULL,
    [Flush Size Max]                 DECIMAL (18)  NULL,
    [Flush Size Min]                 DECIMAL (18)  NULL,
    [Flush Size Avg]                 DECIMAL (18)  NULL,
    [Flush Size StdDev]              DECIMAL (18)  NULL,
    [Flush Size Factor]              DECIMAL (18)  NULL,
    [Flush Pending]                  BIGINT        NULL,
    [Secondary Indexes]              INT           NULL,
    [Materialized Views]             INT           NULL,
    [Common Key]                     VARCHAR (255) NULL,
    [Common Key Factor]              DECIMAL (18)  NULL,
    [Base Table]                     VARCHAR (255) NULL,
    [Base Table Weighted Factor Max] DECIMAL (18)  NULL,
    [Base Table Weighted Factor Avg] DECIMAL (18)  NULL,
    [Reconciliation Reference]       VARCHAR (MAX) NULL, 
    CONSTRAINT [PK_TaggedItems] PRIMARY KEY ([DiagnosticId], [RowId])
);

