CREATE TABLE [dbo].[DataCenters] (
    [DiagnosticId]			   VARCHAR (115) NOT NULL,
	[Data Center]                  VARCHAR (100) NOT NULL,
    [Total Nodes]                  BIGINT        NULL,
    [Cassandra]                    BIGINT        NULL,
    [Search]                       BIGINT        NULL,
    [Analytics]                    BIGINT        NULL,
    [Graph]                        BIGINT        NULL,
    [Multi-Instance]               BIGINT        NULL,
    [Other]                        BIGINT        NULL,
    [Status Up]                    BIGINT        NULL,
    [Status Down]                  BIGINT        NULL,
    [Status Unknown]               BIGINT        NULL,
    [Status Starts]                BIGINT        NULL,
    [Status Restarts]              BIGINT        NULL,
    [Long Down Pause]              BIGINT        NULL,
    [Status Not Responding]        BIGINT        NULL,
    [Status Dead]                  BIGINT        NULL,
    [Network Events]               BIGINT        NULL,
    [Status Other]                 BIGINT        NULL,
    [DSE Version]                  VARCHAR (25) NULL,
    [DU Max]                       DECIMAL (18)  NULL,
    [DU Max-Node]                  VARCHAR (45) NULL,
    [DU Min]                       DECIMAL (18)  NULL,
    [DU Min-Node]                  VARCHAR (45) NULL,
    [DU Avg]                       DECIMAL (18)  NULL,
    [DU Insufficient Space]        BIGINT        NULL,
    [Storage Max]                  DECIMAL (18)  NULL,
    [Storage Max-Node]             VARCHAR (45) NULL,
    [Storage Min]                  DECIMAL (18)  NULL,
    [Storage Min-Node]             VARCHAR (45) NULL,
    [Storage Avg]                  DECIMAL (18)  NULL,
    [Storage Total]                DECIMAL (18)  NULL,
    [Storage Total (User)]         DECIMAL (18)  NULL,
    [Storage Percent]              DECIMAL (18)  NULL,
    [SSTables Max]                 BIGINT        NULL,
    [SSTables Max-Node]            VARCHAR (45) NULL,
    [SSTables Min]                 BIGINT        NULL,
    [SSTables Min-Node]            VARCHAR (45) NULL,
    [SSTables Avg]                 DECIMAL (18)  NULL,
    [SSTables StdDev]              REAL          NULL,
    [SSTables Total]               BIGINT        NULL,
    [SSTables Total (User)]        BIGINT        NULL,
    [SSTables Percent]             DECIMAL (18)  NULL,
    [Distribution Storage From]    DECIMAL (18)  NULL,
    [Distribution Storage To]      DECIMAL (18)  NULL,
    [Distribution Storage StdDev]  REAL          NULL,
    [Distribution Keys From]       DECIMAL (18)  NULL,
    [Distribution Keys To]         DECIMAL (18)  NULL,
    [Distribution Keys StdDev]     REAL          NULL,
    [Distribution SSTables From]   DECIMAL (18)  NULL,
    [Distribution SSTables To]     DECIMAL (18)  NULL,
    [Distribution SSTables StdDev] REAL          NULL,
    [Active Tbls/Idxs/Vws]         DECIMAL (18)  NULL,
    [Reads Max]                    BIGINT        NULL,
    [Reads Max-Node]               VARCHAR (45) NULL,
    [Reads Min]                    BIGINT        NULL,
    [Reads Min-Node]               VARCHAR (45) NULL,
    [Reads Avg]                    DECIMAL (18)  NULL,
    [Reads StdDev]                 REAL          NULL,
    [Reads Total]                  BIGINT        NULL,
    [Reads Total (User)]           BIGINT        NULL,
    [Reads Percent]                DECIMAL (18)  NULL,
    [Writes Max]                   BIGINT        NULL,
    [Writes Max-Node]              VARCHAR (45) NULL,
    [Writes Min]                   BIGINT        NULL,
    [Writes Min-Node]              VARCHAR (45) NULL,
    [Writes Avg]                   DECIMAL (18)  NULL,
    [Writes StdDev]                REAL          NULL,
    [Writes Total]                 BIGINT        NULL,
    [Writes Total (User)]          BIGINT        NULL,
    [Writes Percent]               DECIMAL (18)  NULL,
    [Batch Percent]                DECIMAL (18)  NULL,
    [LWT Percent]                  DECIMAL (18)  NULL,
    [Log Event Total]              BIGINT        NULL,
    [Log Event Percent]            DECIMAL (18)  NULL,
    [GC Events Total]              BIGINT        NULL,
    [GC Events Percent]            DECIMAL (18)  NULL,
    [Flush Total]                  BIGINT        NULL,
    [Flush Total (User)]           BIGINT        NULL,
    [Flush Percent]                DECIMAL (18)  NULL,
    [Compaction Total]             BIGINT        NULL,
    [Compaction Total (User)]      BIGINT        NULL,
    [Compaction Percent]           DECIMAL (18)  NULL,
    [Repair Total]                 BIGINT        NULL,
    [Repair Total (User)]          BIGINT        NULL,
    [Repair Percent]               DECIMAL (18)  NULL,
    [Repair Est Tasks (User)]      BIGINT        NULL,
    [Node Sync Tables (User)]      BIGINT        NULL,
    [Node Sync Count]              BIGINT        NULL,
    [Diagnostic Data Quality]      VARCHAR (25) NULL,
    [Node UpTime]                  BIGINT        NULL,
    [Log System Duration]          BIGINT        NULL,
    [Log Debug Duration]           BIGINT        NULL,
    CONSTRAINT [PK_DataCenters] PRIMARY KEY CLUSTERED ([DiagnosticId], [Data Center])
);

