CREATE TABLE [dbo].[Nodes] (
	[DiagnosticId]				  VARCHAR (115) NOT NULL,
    [Node IPAddress]                VARCHAR (55) NOT NULL,
    [Data Center]                   VARCHAR (100) NULL,
    [Rack]                          VARCHAR (100) NULL,
    [Status]                        VARCHAR (25) NULL,
    [Instance Type]                 VARCHAR (50) NULL,
    [Cluster Name]                  VARCHAR (100) NULL,
    [DSE]                           VARCHAR (25) NULL,
    [Cassandra]                     VARCHAR (25) NULL,
    [Search]                        VARCHAR (25) NULL,
    [Spark]                         VARCHAR (25) NULL,
    [Agent]                         VARCHAR (25) NULL,
    [Schema]                        VARCHAR (38) NULL,
    [Status Starts]                 BIGINT        NULL,
    [Status Restarts]               BIGINT        NULL,
    [Long Down Pause]               BIGINT        NULL,
    [Status Not Responding]         BIGINT        NULL,
    [Status Dead]                   BIGINT        NULL,
    [Network Events]                BIGINT        NULL,
    [Status Other]                  BIGINT        NULL,
    [Device Utilized]               DECIMAL (18)  NULL,
    [DU Insufficient Space]         BIGINT        NULL,
    [Storage Total]                 DECIMAL (18)  NULL,
    [Storage Total (User)]          DECIMAL (18)  NULL,
    [Storage Percent]               DECIMAL (18)  NULL,
    [SSTables Total]                BIGINT        NULL,
    [SSTables Total (User)]         BIGINT        NULL,
    [SSTables Percent]              DECIMAL (18)  NULL,
    [Reads Total]                   BIGINT        NULL,
    [Reads Total (User)]            BIGINT        NULL,
    [Reads Percent]                 DECIMAL (18)  NULL,
    [Writes Total]                  BIGINT        NULL,
    [Writes Total (User)]           BIGINT        NULL,
    [Writes Percent]                DECIMAL (18)  NULL,
    [Batch Percent]                 DECIMAL (18)  NULL,
    [LWT Percent]                   DECIMAL (18)  NULL,
    [Log Event Total]               BIGINT        NULL,
    [Log Event Percent]             DECIMAL (18)  NULL,
    [GC Events Total]               BIGINT        NULL,
    [GC Events Percent]             DECIMAL (18)  NULL,
    [Flush Total]                   BIGINT        NULL,
    [Flush Total (User)]            BIGINT        NULL,
    [Flush Percent]                 DECIMAL (18)  NULL,
    [Compaction Total]              BIGINT        NULL,
    [Compaction Total (User)]       BIGINT        NULL,
    [Compaction Percent]            DECIMAL (18)  NULL,
    [Repair Total]                  BIGINT        NULL,
    [Repair Total (User)]           BIGINT        NULL,
    [Repair Percent]                DECIMAL (18)  NULL,
    [Repair Est Tasks (User)]       BIGINT        NULL,
    [Node Sync Tables (User)]       BIGINT        NULL,
    [Node Sync Count]               BIGINT        NULL,
    [Diagnostic Data Quality]       VARCHAR (255) NULL,
    [Time Zone Offset]              VARCHAR (255) NULL,
    [Start NodeTool Range]          DATETIME      NULL,
    [End NodeTool Range]            DATETIME      NULL,
    [Uptime]                        BIGINT        NULL,
    [Log Min Timestamp]             DATETIME      NULL,
    [Log Max Timestamp]             DATETIME      NULL,
    [Log Duration]                  BIGINT        NULL,
    [Log Timespan Difference]       BIGINT        NULL,
    [Log Nbr Files]                 INT           NULL,
    [Debug Log Min Timestamp]       DATETIME      NULL,
    [Debug Log Max Timestamp]       DATETIME      NULL,
    [Debug Log Duration]            BIGINT        NULL,
    [Debug Log Timespan Difference] BIGINT        NULL,
    [Debug Log Nbr Files]           INT           NULL,
    [VNodes]                        BIT           NULL,
    [Nbr VNodes]                    INT           NULL,
    [Repair Service Enabled]        BIT           NULL,
    [Seed Node]                     BIT           NULL,
    [Gossip Enabled]                BIT           NULL,
    [Thrift Enabled]                BIT           NULL,
    [Native Transport Enabled]      BIT           NULL,
    [Multi-Instance Server Id]      VARCHAR (38) NULL,
    [Key Cache Information]         VARCHAR (MAX) NULL,
    [Row Cache Information]         VARCHAR (MAX) NULL,
    [Counter Cache Information]     VARCHAR (MAX) NULL,
    [Chunk Cache Information]       VARCHAR (MAX) NULL,
    CONSTRAINT [PK_Nodes] PRIMARY KEY CLUSTERED ([DiagnosticId] ASC, [Node IPAddress] ASC)
);

