CREATE TABLE [dbo].[Keyspaces] (
	[DiagnosticId]				VARCHAR (115) NOT NULL,			   
    [Name]                     VARCHAR (100) NOT NULL,
    [Data Center]              VARCHAR (100) NOT NULL,
    [Replication Strategy]     VARCHAR (100) NULL,
    [Replication Factor]       INT           NULL,
    [Tables]                   INT           NULL,
    [Views]                    INT           NULL,
    [Secondary Indexes]        INT           NULL,
    [solr Indexes]             INT           NULL,
    [SAS Indexes]              INT           NULL,
    [Custom Indexes]           INT           NULL,
    [Functions]                INT           NULL,
    [Triggers]                 INT           NULL,
    [User Defined Types]       INT           NULL,
    [Total]                    INT           NULL,
    [Active]                   INT           NULL,
    [Active Percent]           DECIMAL (18)  NULL,
    [STCS]                     INT           NULL,
    [LCS]                      INT           NULL,
    [DTCS]                     INT           NULL,
    [TCS]                      INT           NULL,
    [TWCS]                     INT           NULL,
    [Other Strategies]         INT           NULL,
    [Column Total]             INT           NULL,
    [Column Collections]       INT           NULL,
    [Column Blobs]             INT           NULL,
    [Column Static]            INT           NULL,
    [Column Frozen]            INT           NULL,
    [Column Tuple]             INT           NULL,
    [Column UDT]               INT           NULL,
    [Read-Repair Chance (Max)] DECIMAL (18)  NULL,
    [Read-Repair DC Chance]    DECIMAL (18)  NULL,
    [GC Grace (Max)]           BIGINT        NULL,
    [TTL (Max)]                BIGINT        NULL,
    [OrderBy]                  INT           NULL,
    [Compact Storage]          INT           NULL,
    [Node Sync]                INT           NULL,
    [Storage (MB)]             DECIMAL (18)  NULL,
    [Storage Utilized]         DECIMAL (18)  NULL,
    [Read Percent]             DECIMAL (18)  NULL,
    [Write Percent]            DECIMAL (18)  NULL,
    [Partition Keys]           BIGINT        NULL,
    [Key Percent]              DECIMAL (18)  NULL,
    [SSTable]                  BIGINT        NULL,
    [SSTable Percent]          DECIMAL (18)  NULL,
    [Flush Percent]            DECIMAL (18)  NULL,
    [Compaction Percent]       DECIMAL (18)  NULL,
    [Repair Percent]           DECIMAL (18)  NULL,
    [DDL]                      VARCHAR (MAX) NULL,
    CONSTRAINT [PK_Keyspaces] PRIMARY KEY CLUSTERED ([DiagnosticId] ASC, [Name] ASC, [Data Center] ASC)
);

