CREATE TABLE [dbo].[Servers] (
	[DiagnosticId]		   VARCHAR (115) NOT NULL,
    [Node IPAddress]       VARCHAR (55) NOT NULL,
    [Data Center]          VARCHAR (100) NULL,
    [Cloud-VM Type]        VARCHAR (100) NULL,
    [CPU Architecture]     VARCHAR (100) NULL,
    [Cores]                INT           NULL,
    [Physical Memory (MB)] INT           NULL,
    [OS]                   VARCHAR (100) NULL,
    [OS Version]           VARCHAR (25) NULL,
    [Kernel]               VARCHAR (100) NULL,
    [TimeZone]             VARCHAR (100) NULL,
    [Average]              DECIMAL (18)  NULL,
    [Idle]                 DECIMAL (18)  NULL,
    [System]               DECIMAL (18)  NULL,
    [User]                 DECIMAL (18)  NULL,
    [IOWait]               DECIMAL (18)  NULL,
    [StealTime]            DECIMAL (18)  NULL,
    [Available]            INT           NULL,
    [Cache]                INT           NULL,
    [Buffers]              INT           NULL,
    [Shared]               INT           NULL,
    [Free]                 INT           NULL,
    [Used]                 INT           NULL,
    [Vendor]               VARCHAR (255) NULL,
    [Model]                VARCHAR (255) NULL,
    [Runtime Name]         VARCHAR (255) NULL,
    [Runtime Version]      VARCHAR (25) NULL,
    [GC]                   VARCHAR (25) NULL,
    [Non-Heap Committed]   DECIMAL (18)  NULL,
    [Non-Heap Init]        DECIMAL (18)  NULL,
    [Non-Heap Max]         DECIMAL (18)  NULL,
    [Non-Heap Used]        DECIMAL (18)  NULL,
    [Heap Committed]       DECIMAL (18)  NULL,
    [Heap Init]            DECIMAL (18)  NULL,
    [Heap Max]             DECIMAL (18)  NULL,
    [Heap Used]            DECIMAL (18)  NULL,
    [Correction (ms)]      INT           NULL,
    [Polling (secs)]       INT           NULL,
    [Maximum Error (us)]   INT           NULL,
    [Estimated Error (us)] INT           NULL,
    [Time Constant]        INT           NULL,
    [Precision (us)]       DECIMAL (18)  NULL,
    [Frequency (ppm)]      DECIMAL (18)  NULL,
    [Tolerance (ppm)]      DECIMAL (18)  NULL,
    [Host Names]           VARCHAR (255) NULL,
    CONSTRAINT [PK_Servers] PRIMARY KEY CLUSTERED ([DiagnosticId] ASC, [Node IPAddress] ASC)
);

