CREATE TABLE [dbo].[CQLDDL] (
    [DiagnosticId]			   VARCHAR (115) NOT NULL,
	[Active]                BIT           NULL,
    [Keyspace Name]         VARCHAR (255) NOT NULL,
    [Name]                  VARCHAR (255) NOT NULL,
    [Type]                  VARCHAR (15) NULL,
    [Partition Key]         VARCHAR (255) NULL,
    [Cluster Key]           VARCHAR (255) NULL,
    [Compaction Strategy]   VARCHAR (255) NULL,
    [Compression]           VARCHAR (255) NULL,
    [Chance]                DECIMAL (18)  NULL,
    [DC Chance]             DECIMAL (18)  NULL,
    [Policy]                VARCHAR (255) NULL,
    [GC Grace Period]       BIGINT        NULL,
    [TTL]                   BIGINT        NULL,
    [Memtable Flush Period] BIGINT        NULL,
    [Collections]           INT           NULL,
    [Counters]              INT           NULL,
    [Blobs]                 INT           NULL,
    [Static]                INT           NULL,
    [Frozen]                INT           NULL,
    [Tuple]                 INT           NULL,
    [UDT]                   INT           NULL,
    [Total]                 INT           NULL,
    [HasOrderBy]            BIT           NULL,
    [Compact Storage]       BIT           NULL,
    [Node Sync]             BIT           NULL,
    [Associated Table]      VARCHAR (255) NULL,
    [Index]                 BIT           NULL,
    [NbrIndexes]            INT           NULL,
    [NbrMVs]                INT           NULL,
    [NbrTriggers]           INT           NULL,
    [Storage (MB)]          DECIMAL (18)  NULL,
    [Storage Utilized]      DECIMAL (18)  NULL,
    [Read Percent]          DECIMAL (18)  NULL,
    [Write Percent]         DECIMAL (18)  NULL,
    [Partition Keys]        BIGINT        NULL,
    [Key Percent]           DECIMAL (18)  NULL,
    [SSTable]               BIGINT        NULL,
    [SSTable Percent]       DECIMAL (18)  NULL,
    [Flush Percent]         DECIMAL (18)  NULL,
    [Compaction Percent]    DECIMAL (18)  NULL,
    [Repair Percent]        DECIMAL (18)  NULL,
    [DDL]                   VARCHAR (MAX) NULL,
    CONSTRAINT [PK_CQLDDL] PRIMARY KEY CLUSTERED ([DiagnosticId] ASC, [Keyspace Name] ASC, [Name] ASC)
);

