CREATE TABLE [dbo].[LogAggregation] (
	[DiagnosticId]				  VARCHAR (115) NOT NULL,
	[RowId]						  BIGINT NOT NULL,
    [UTC Timestamp]               DATETIME      NOT NULL,
    [Log Local Timestamp]         DATETIME      NULL,
    [Aggregation Period]          BIGINT        NULL,
    [Data Center]                 VARCHAR (100) NOT NULL,
    [Node IPAddress]              VARCHAR (55) NOT NULL,
    [Keyspace Name]               VARCHAR (255) NULL,
    [Table Name]                  VARCHAR (MAX) NULL,
    [Class]                       VARCHAR (255) NOT NULL,
    [Related Info]                VARCHAR (MAX) NULL,
    [HasOrphanedEvents]           BIT           NULL,
    [Path]                        VARCHAR (MAX) NULL,
    [Exception]                   VARCHAR (MAX) NULL,
    [Last Occurrence (UTC)]       DATETIME      NULL,
    [Last Occurrence (Local)]     DATETIME      NULL,
    [Occurrences]                 BIGINT        NULL,
    [UOM]                         VARCHAR (255) NULL,
    [Duration Max]                DECIMAL (18)  NULL,
    [Duration Min]                DECIMAL (18)  NULL,
    [Duration Mean]               DECIMAL (18)  NULL,
    [Duration StdDevp]            DECIMAL (18)  NULL,
    [Duration Total]              DECIMAL (18)  NULL,
    [Rate Max]                    DECIMAL (18)  NULL,
    [Rate Min]                    DECIMAL (18)  NULL,
    [Rate Mean]                   DECIMAL (18)  NULL,
    [Rate StdDevp]                DECIMAL (18)  NULL,
    [Pending|Tombstone]           BIGINT        NULL,
    [Completed|Live]              BIGINT        NULL,
    [Blocked]                     BIGINT        NULL,
    [AllTimeBlocked]              BIGINT        NULL,
    [EdenThresholdReadRateMax]    DECIMAL (18)  NULL,
    [EdenDifThresholdReadRateMin] DECIMAL (18)  NULL,
    [OldThresholdReadRateMean]    DECIMAL (18)  NULL,
    [OldThresholdReadRateStdDevp] DECIMAL (18)  NULL,
    [Survivor Max]                DECIMAL (18)  NULL,
    [Survivor Dif]                DECIMAL (18)  NULL,
    [Size Max]                    DECIMAL (18)  NULL,
    [Size Min]                    DECIMAL (18)  NULL,
    [Size Mean]                   DECIMAL (18)  NULL,
    [Size StdDevp]                DECIMAL (18)  NULL,
    [Size Total]                  DECIMAL (18)  NULL,
    [Count Max]                   BIGINT        NULL,
    [Count Min]                   BIGINT        NULL,
    [Count Mean]                  DECIMAL (18)  NULL,
    [Count StdDevp]               DECIMAL (18)  NULL,
    [Count Total]                 BIGINT        NULL,
    [OPS Max]                     BIGINT        NULL,
    [OPS Min]                     BIGINT        NULL,
    [OPS Mean]                    DECIMAL (18)  NULL,
    [OPS StdDevp]                 DECIMAL (18)  NULL,
    [Serialized Max]              DECIMAL (18)  NULL,
    [Serialized Min]              DECIMAL (18)  NULL,
    [Serialized Mean]             DECIMAL (18)  NULL,
    [Serialized StdDevp]          DECIMAL (18)  NULL,
    [Serialized Total]            DECIMAL (18)  NULL,
    [Storage Max]                 DECIMAL (18)  NULL,
    [Storage Min]                 DECIMAL (18)  NULL,
    [Storage Mean]                DECIMAL (18)  NULL,
    [Storage StdDevp]             DECIMAL (18)  NULL,
    [Storage Total]               DECIMAL (18)  NULL,
    [Reconciliation Reference]    VARCHAR (MAX) NULL, 
    CONSTRAINT [PK_LogAggregation] PRIMARY KEY ([DiagnosticId], [RowId])
);

